/*
 * Poupança
 * <pre>[ Base URL: https://api.sicoob.com.br/poupanca/v3 ]</pre> # Poupança API Sistema que faz a gestão das contas de poupança através de transãções como Aplicação, Resgate, Saldo, Extrato e Controle de Rentabilidade. 
 *
 * The version of the OpenAPI document: 3.0.4.0
 * Contact: marco.martins@sicoob.com.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.sicoob.poupanca.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import br.com.sicoob.poupanca.JSON;

/**
 * TransferenciaDebtorAccount
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-05-04T12:32:58.564497-03:00[America/Sao_Paulo]", comments = "Generator version: 7.22.0")
public class TransferenciaDebtorAccount {
  public static final String SERIALIZED_NAME_ISSUER = "issuer";
  @SerializedName(SERIALIZED_NAME_ISSUER)
  @javax.annotation.Nullable
  private String issuer;

  public static final String SERIALIZED_NAME_NUMBER = "number";
  @SerializedName(SERIALIZED_NAME_NUMBER)
  @javax.annotation.Nullable
  private String number;

  public static final String SERIALIZED_NAME_ACCOUNT_TYPE = "accountType";
  @SerializedName(SERIALIZED_NAME_ACCOUNT_TYPE)
  @javax.annotation.Nullable
  private String accountType;

  public static final String SERIALIZED_NAME_PERSON_TYPE = "personType";
  @SerializedName(SERIALIZED_NAME_PERSON_TYPE)
  @javax.annotation.Nullable
  private String personType;

  public TransferenciaDebtorAccount() {
  }

  public TransferenciaDebtorAccount issuer(@javax.annotation.Nullable String issuer) {
    this.issuer = issuer;
    return this;
  }

  /**
   * Id Instituicao ou Numero Cooperativa
   * @return issuer
   */
  @javax.annotation.Nullable
  public String getIssuer() {
    return issuer;
  }

  public void setIssuer(@javax.annotation.Nullable String issuer) {
    this.issuer = issuer;
  }


  public TransferenciaDebtorAccount number(@javax.annotation.Nullable String number) {
    this.number = number;
    return this;
  }

  /**
   * Numero da Conta
   * @return number
   */
  @javax.annotation.Nullable
  public String getNumber() {
    return number;
  }

  public void setNumber(@javax.annotation.Nullable String number) {
    this.number = number;
  }


  public TransferenciaDebtorAccount accountType(@javax.annotation.Nullable String accountType) {
    this.accountType = accountType;
    return this;
  }

  /**
   * Codigo tipo conta - NATURAL_PERSON (Pessoa Física), LEGAL_PERSON (Pessao Juridica)
   * @return accountType
   */
  @javax.annotation.Nullable
  public String getAccountType() {
    return accountType;
  }

  public void setAccountType(@javax.annotation.Nullable String accountType) {
    this.accountType = accountType;
  }


  public TransferenciaDebtorAccount personType(@javax.annotation.Nullable String personType) {
    this.personType = personType;
    return this;
  }

  /**
   * Codigo tipo pessoa, CACC (Current, Conta Corrente), SLRY (Salary, Conta-Salário), SVGS (Savings, Conta de Poupança), TRAN (TransactingAccount, Conta de Pagamento pré-paga)
   * @return personType
   */
  @javax.annotation.Nullable
  public String getPersonType() {
    return personType;
  }

  public void setPersonType(@javax.annotation.Nullable String personType) {
    this.personType = personType;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransferenciaDebtorAccount transferenciaDebtorAccount = (TransferenciaDebtorAccount) o;
    return Objects.equals(this.issuer, transferenciaDebtorAccount.issuer) &&
        Objects.equals(this.number, transferenciaDebtorAccount.number) &&
        Objects.equals(this.accountType, transferenciaDebtorAccount.accountType) &&
        Objects.equals(this.personType, transferenciaDebtorAccount.personType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(issuer, number, accountType, personType);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransferenciaDebtorAccount {\n");
    sb.append("    issuer: ").append(toIndentedString(issuer)).append("\n");
    sb.append("    number: ").append(toIndentedString(number)).append("\n");
    sb.append("    accountType: ").append(toIndentedString(accountType)).append("\n");
    sb.append("    personType: ").append(toIndentedString(personType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("issuer", "number", "accountType", "personType"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to TransferenciaDebtorAccount
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!TransferenciaDebtorAccount.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in TransferenciaDebtorAccount is not found in the empty JSON string", TransferenciaDebtorAccount.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!TransferenciaDebtorAccount.openapiFields.contains(entry.getKey())) {
          // // throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `TransferenciaDebtorAccount` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
          // Ignoring unknown fields to prevent deserialization errors
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("issuer") != null && !jsonObj.get("issuer").isJsonNull()) && !jsonObj.get("issuer").isJsonPrimitive()) {
        // throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `issuer` to be a primitive type in the JSON string but got `%s`", jsonObj.get("issuer").toString()));
      }
      if ((jsonObj.get("number") != null && !jsonObj.get("number").isJsonNull()) && !jsonObj.get("number").isJsonPrimitive()) {
        // throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `number` to be a primitive type in the JSON string but got `%s`", jsonObj.get("number").toString()));
      }
      if ((jsonObj.get("accountType") != null && !jsonObj.get("accountType").isJsonNull()) && !jsonObj.get("accountType").isJsonPrimitive()) {
        // throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `accountType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("accountType").toString()));
      }
      if ((jsonObj.get("personType") != null && !jsonObj.get("personType").isJsonNull()) && !jsonObj.get("personType").isJsonPrimitive()) {
        // throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `personType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("personType").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TransferenciaDebtorAccount.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TransferenciaDebtorAccount' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TransferenciaDebtorAccount> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TransferenciaDebtorAccount.class));

       return (TypeAdapter<T>) new TypeAdapter<TransferenciaDebtorAccount>() {
           @Override
           public void write(JsonWriter out, TransferenciaDebtorAccount value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public TransferenciaDebtorAccount read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of TransferenciaDebtorAccount given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of TransferenciaDebtorAccount
   * @throws IOException if the JSON string is invalid with respect to TransferenciaDebtorAccount
   */
  public static TransferenciaDebtorAccount fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TransferenciaDebtorAccount.class);
  }

  /**
   * Convert an instance of TransferenciaDebtorAccount to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

