/*
 * Sicoob Autenticação
 * API independente para geração de tokens de acesso mTLS via Client Credentials.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.sicoob.auth.api;

import br.com.sicoob.auth.ApiException;
import br.com.sicoob.auth.model.AuthRealmsCooperadoProtocolOpenidConnectTokenPost200Response;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AutenticaoApi
 */
@Disabled
public class AutenticaoApiTest {

    private final AutenticaoApi api = new AutenticaoApi();

    /**
     * Gerar token de acesso
     *
     * Endpoint para geração de token de acesso via Client Credentials com mTLS.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void authRealmsCooperadoProtocolOpenidConnectTokenPostTest() throws ApiException {
        String grantType = null;
        String clientId = null;
        String scope = null;
        AuthRealmsCooperadoProtocolOpenidConnectTokenPost200Response response = api.authRealmsCooperadoProtocolOpenidConnectTokenPost(grantType, clientId, scope);
        // TODO: test validations
    }

}
