/*
 * SPB Transferências
 * <pre>[ Base URL: https://api.sicoob.com.br/spb/v2 ]</pre> A API tem como propósito fornecer serviços para envio de TEDs.
 *
 * The version of the OpenAPI document: 1.0.4.2
 * Contact: rayana.silva@sicoob.com.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.sicoob.spbtransferencias.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import br.com.sicoob.spbtransferencias.JSON;

/**
 * DadosRetornoTedCanceladaDTO
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-05-04T12:33:00.929742-03:00[America/Sao_Paulo]", comments = "Generator version: 7.22.0")
public class DadosRetornoTedCanceladaDTO {
  public static final String SERIALIZED_NAME_MENSAGEM = "mensagem";
  @SerializedName(SERIALIZED_NAME_MENSAGEM)
  @javax.annotation.Nullable
  private String mensagem;

  public DadosRetornoTedCanceladaDTO() {
  }

  public DadosRetornoTedCanceladaDTO mensagem(@javax.annotation.Nullable String mensagem) {
    this.mensagem = mensagem;
    return this;
  }

  /**
   * Mensagem de retorno do cancelamento.
   * @return mensagem
   */
  @javax.annotation.Nullable
  public String getMensagem() {
    return mensagem;
  }

  public void setMensagem(@javax.annotation.Nullable String mensagem) {
    this.mensagem = mensagem;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DadosRetornoTedCanceladaDTO dadosRetornoTedCanceladaDTO = (DadosRetornoTedCanceladaDTO) o;
    return Objects.equals(this.mensagem, dadosRetornoTedCanceladaDTO.mensagem);
  }

  @Override
  public int hashCode() {
    return Objects.hash(mensagem);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DadosRetornoTedCanceladaDTO {\n");
    sb.append("    mensagem: ").append(toIndentedString(mensagem)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("mensagem"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to DadosRetornoTedCanceladaDTO
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!DadosRetornoTedCanceladaDTO.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in DadosRetornoTedCanceladaDTO is not found in the empty JSON string", DadosRetornoTedCanceladaDTO.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!DadosRetornoTedCanceladaDTO.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `DadosRetornoTedCanceladaDTO` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("mensagem") != null && !jsonObj.get("mensagem").isJsonNull()) && !jsonObj.get("mensagem").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `mensagem` to be a primitive type in the JSON string but got `%s`", jsonObj.get("mensagem").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!DadosRetornoTedCanceladaDTO.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'DadosRetornoTedCanceladaDTO' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<DadosRetornoTedCanceladaDTO> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(DadosRetornoTedCanceladaDTO.class));

       return (TypeAdapter<T>) new TypeAdapter<DadosRetornoTedCanceladaDTO>() {
           @Override
           public void write(JsonWriter out, DadosRetornoTedCanceladaDTO value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public DadosRetornoTedCanceladaDTO read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of DadosRetornoTedCanceladaDTO given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of DadosRetornoTedCanceladaDTO
   * @throws IOException if the JSON string is invalid with respect to DadosRetornoTedCanceladaDTO
   */
  public static DadosRetornoTedCanceladaDTO fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, DadosRetornoTedCanceladaDTO.class);
  }

  /**
   * Convert an instance of DadosRetornoTedCanceladaDTO to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

