/*
 * Cobrança Bancária Pagamentos
 * <pre>[ Base URL: https://api.sicoob.com.br/pagamentos/v3 ]</pre> Esta API disponibiliza funcionalidades para realização de pagamentos de boletos de Cobrança Bancária.
 *
 * The version of the OpenAPI document: 3.0.2.0
 * Contact: GrupoGesin1CobrancaBancaria@sicoob.com.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.sicoob.pagamentosv3.model;

import br.com.sicoob.pagamentosv3.model.BoletoConsulta;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for BoletosCodigoBarrasGet200Response
 */
public class BoletosCodigoBarrasGet200ResponseTest {
    private final BoletosCodigoBarrasGet200Response model = new BoletosCodigoBarrasGet200Response();

    /**
     * Model tests for BoletosCodigoBarrasGet200Response
     */
    @Test
    public void testBoletosCodigoBarrasGet200Response() {
        // TODO: test BoletosCodigoBarrasGet200Response
    }

    /**
     * Test the property 'resultado'
     */
    @Test
    public void resultadoTest() {
        // TODO: test resultado
    }

}
