/*
 * Cobrança Bancária Pagamentos
 * <pre>[ Base URL: https://api.sicoob.com.br/pagamentos/v3 ]</pre> Esta API disponibiliza funcionalidades para realização de pagamentos de boletos de Cobrança Bancária.
 *
 * The version of the OpenAPI document: 3.0.2.0
 * Contact: GrupoGesin1CobrancaBancaria@sicoob.com.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.sicoob.pagamentosv3.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for BoletoDDA
 */
public class BoletoDDATest {
    private final BoletoDDA model = new BoletoDDA();

    /**
     * Model tests for BoletoDDA
     */
    @Test
    public void testBoletoDDA() {
        // TODO: test BoletoDDA
    }

    /**
     * Test the property 'descricaoTipoPagador'
     */
    @Test
    public void descricaoTipoPagadorTest() {
        // TODO: test descricaoTipoPagador
    }

    /**
     * Test the property 'tipoPessoaBeneficiario'
     */
    @Test
    public void tipoPessoaBeneficiarioTest() {
        // TODO: test tipoPessoaBeneficiario
    }

    /**
     * Test the property 'numeroCpfCnpjBeneficiario'
     */
    @Test
    public void numeroCpfCnpjBeneficiarioTest() {
        // TODO: test numeroCpfCnpjBeneficiario
    }

    /**
     * Test the property 'nomeRazaoSocialBeneficiario'
     */
    @Test
    public void nomeRazaoSocialBeneficiarioTest() {
        // TODO: test nomeRazaoSocialBeneficiario
    }

    /**
     * Test the property 'tipoPessoaPagador'
     */
    @Test
    public void tipoPessoaPagadorTest() {
        // TODO: test tipoPessoaPagador
    }

    /**
     * Test the property 'numeroCpfCnpjPagador'
     */
    @Test
    public void numeroCpfCnpjPagadorTest() {
        // TODO: test numeroCpfCnpjPagador
    }

    /**
     * Test the property 'nomeRazaoSocialPagador'
     */
    @Test
    public void nomeRazaoSocialPagadorTest() {
        // TODO: test nomeRazaoSocialPagador
    }

    /**
     * Test the property 'nomeFantasiaPagador'
     */
    @Test
    public void nomeFantasiaPagadorTest() {
        // TODO: test nomeFantasiaPagador
    }

    /**
     * Test the property 'descricaoLogradouroPagador'
     */
    @Test
    public void descricaoLogradouroPagadorTest() {
        // TODO: test descricaoLogradouroPagador
    }

    /**
     * Test the property 'descricaoCidadePagador'
     */
    @Test
    public void descricaoCidadePagadorTest() {
        // TODO: test descricaoCidadePagador
    }

    /**
     * Test the property 'siglaUfPagador'
     */
    @Test
    public void siglaUfPagadorTest() {
        // TODO: test siglaUfPagador
    }

    /**
     * Test the property 'numeroCepPagador'
     */
    @Test
    public void numeroCepPagadorTest() {
        // TODO: test numeroCepPagador
    }

    /**
     * Test the property 'tipoPessoaAvalista'
     */
    @Test
    public void tipoPessoaAvalistaTest() {
        // TODO: test tipoPessoaAvalista
    }

    /**
     * Test the property 'numeroCpfCnpjAvalista'
     */
    @Test
    public void numeroCpfCnpjAvalistaTest() {
        // TODO: test numeroCpfCnpjAvalista
    }

    /**
     * Test the property 'nomeAvalista'
     */
    @Test
    public void nomeAvalistaTest() {
        // TODO: test nomeAvalista
    }

    /**
     * Test the property 'valorBoleto'
     */
    @Test
    public void valorBoletoTest() {
        // TODO: test valorBoleto
    }

    /**
     * Test the property 'dataVencimentoBoleto'
     */
    @Test
    public void dataVencimentoBoletoTest() {
        // TODO: test dataVencimentoBoleto
    }

    /**
     * Test the property 'codigoTipoSituacaoBoleto'
     */
    @Test
    public void codigoTipoSituacaoBoletoTest() {
        // TODO: test codigoTipoSituacaoBoleto
    }

    /**
     * Test the property 'descricaoSituacaoBoleto'
     */
    @Test
    public void descricaoSituacaoBoletoTest() {
        // TODO: test descricaoSituacaoBoleto
    }

    /**
     * Test the property 'numeroIdentificadorBoletoCip'
     */
    @Test
    public void numeroIdentificadorBoletoCipTest() {
        // TODO: test numeroIdentificadorBoletoCip
    }

    /**
     * Test the property 'numeroCodigoBarras'
     */
    @Test
    public void numeroCodigoBarrasTest() {
        // TODO: test numeroCodigoBarras
    }

    /**
     * Test the property 'numeroCpfCnpjPagadorEletronico'
     */
    @Test
    public void numeroCpfCnpjPagadorEletronicoTest() {
        // TODO: test numeroCpfCnpjPagadorEletronico
    }

    /**
     * Test the property 'aceite'
     */
    @Test
    public void aceiteTest() {
        // TODO: test aceite
    }

    /**
     * Test the property 'numeroNossoNumero'
     */
    @Test
    public void numeroNossoNumeroTest() {
        // TODO: test numeroNossoNumero
    }

    /**
     * Test the property 'numeroDocumento'
     */
    @Test
    public void numeroDocumentoTest() {
        // TODO: test numeroDocumento
    }

    /**
     * Test the property 'dataPagamento'
     */
    @Test
    public void dataPagamentoTest() {
        // TODO: test dataPagamento
    }

    /**
     * Test the property 'valorPagamento'
     */
    @Test
    public void valorPagamentoTest() {
        // TODO: test valorPagamento
    }

    /**
     * Test the property 'codigoEspecieDocumento'
     */
    @Test
    public void codigoEspecieDocumentoTest() {
        // TODO: test codigoEspecieDocumento
    }

    /**
     * Test the property 'dataEmissao'
     */
    @Test
    public void dataEmissaoTest() {
        // TODO: test dataEmissao
    }

    /**
     * Test the property 'dataLimitePagamento'
     */
    @Test
    public void dataLimitePagamentoTest() {
        // TODO: test dataLimitePagamento
    }

    /**
     * Test the property 'codigoTipoJuros'
     */
    @Test
    public void codigoTipoJurosTest() {
        // TODO: test codigoTipoJuros
    }

    /**
     * Test the property 'dataJuros'
     */
    @Test
    public void dataJurosTest() {
        // TODO: test dataJuros
    }

    /**
     * Test the property 'valorPercentualJuros'
     */
    @Test
    public void valorPercentualJurosTest() {
        // TODO: test valorPercentualJuros
    }

    /**
     * Test the property 'codigoTipoMulta'
     */
    @Test
    public void codigoTipoMultaTest() {
        // TODO: test codigoTipoMulta
    }

    /**
     * Test the property 'dataMulta'
     */
    @Test
    public void dataMultaTest() {
        // TODO: test dataMulta
    }

    /**
     * Test the property 'valorPercentualMulta'
     */
    @Test
    public void valorPercentualMultaTest() {
        // TODO: test valorPercentualMulta
    }

    /**
     * Test the property 'valorAbatimento'
     */
    @Test
    public void valorAbatimentoTest() {
        // TODO: test valorAbatimento
    }

    /**
     * Test the property 'codigoTipoDesconto1'
     */
    @Test
    public void codigoTipoDesconto1Test() {
        // TODO: test codigoTipoDesconto1
    }

    /**
     * Test the property 'dataDesconto1'
     */
    @Test
    public void dataDesconto1Test() {
        // TODO: test dataDesconto1
    }

    /**
     * Test the property 'valorPercentualDesconto1'
     */
    @Test
    public void valorPercentualDesconto1Test() {
        // TODO: test valorPercentualDesconto1
    }

    /**
     * Test the property 'codigoTipoDesconto2'
     */
    @Test
    public void codigoTipoDesconto2Test() {
        // TODO: test codigoTipoDesconto2
    }

    /**
     * Test the property 'dataDesconto2'
     */
    @Test
    public void dataDesconto2Test() {
        // TODO: test dataDesconto2
    }

    /**
     * Test the property 'valorPercentualDesconto2'
     */
    @Test
    public void valorPercentualDesconto2Test() {
        // TODO: test valorPercentualDesconto2
    }

    /**
     * Test the property 'codigoTipoDesconto3'
     */
    @Test
    public void codigoTipoDesconto3Test() {
        // TODO: test codigoTipoDesconto3
    }

    /**
     * Test the property 'dataDesconto3'
     */
    @Test
    public void dataDesconto3Test() {
        // TODO: test dataDesconto3
    }

    /**
     * Test the property 'valorPercentualDesconto3'
     */
    @Test
    public void valorPercentualDesconto3Test() {
        // TODO: test valorPercentualDesconto3
    }

    /**
     * Test the property 'numeroDiasProtesto'
     */
    @Test
    public void numeroDiasProtestoTest() {
        // TODO: test numeroDiasProtesto
    }

    /**
     * Test the property 'quantidadePagamentoParcial'
     */
    @Test
    public void quantidadePagamentoParcialTest() {
        // TODO: test quantidadePagamentoParcial
    }

    /**
     * Test the property 'codigoAutorizacaoValorDivergente'
     */
    @Test
    public void codigoAutorizacaoValorDivergenteTest() {
        // TODO: test codigoAutorizacaoValorDivergente
    }

    /**
     * Test the property 'codigoIndicadorValorMaximo'
     */
    @Test
    public void codigoIndicadorValorMaximoTest() {
        // TODO: test codigoIndicadorValorMaximo
    }

    /**
     * Test the property 'valorPercentualMaximo'
     */
    @Test
    public void valorPercentualMaximoTest() {
        // TODO: test valorPercentualMaximo
    }

    /**
     * Test the property 'codigoIndicadorValorMinimo'
     */
    @Test
    public void codigoIndicadorValorMinimoTest() {
        // TODO: test codigoIndicadorValorMinimo
    }

    /**
     * Test the property 'valorPercentualMinimo'
     */
    @Test
    public void valorPercentualMinimoTest() {
        // TODO: test valorPercentualMinimo
    }

}
