/*
 * Cobrança Bancária
 * <pre>[ Base URL: https://api.sicoob.com.br/cobranca-bancaria/v3 ]</pre> A Cobrança Bancária Sicoob é um conjunto de serviços oferecidos a seus associados para recebimento de valores referentes às vendas de produtos e serviços da sua empresa, por meio de boletos de cobrança, pagos em toda a rede bancária. Esta API disponibiliza funcionalidades que auxiliam na gestão da carteira registrada, tornando viável todo o processo de acompanhamento, desde a inclusão de novos boletos, alteração de informações relevantes, protesto/negativação de títulos vencidos e não pagos, até a liquidação ou baixa do título.
 *
 * The version of the OpenAPI document: 3.0.8.0
 * Contact: GrupoGesin1CobrancaBancaria@sicoob.com.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.sicoob.cobrancav3.model;

import java.util.Objects;
import br.com.sicoob.cobrancav3.model.BoletoAlteracaoAbatimento;
import br.com.sicoob.cobrancav3.model.BoletoAlteracaoDesconto;
import br.com.sicoob.cobrancav3.model.BoletoAlteracaoEspecieDocumento;
import br.com.sicoob.cobrancav3.model.BoletoAlteracaoJurosMora;
import br.com.sicoob.cobrancav3.model.BoletoAlteracaoMulta;
import br.com.sicoob.cobrancav3.model.BoletoAlteracaoPix;
import br.com.sicoob.cobrancav3.model.BoletoAlteracaoProrrogacaoLimitePagamento;
import br.com.sicoob.cobrancav3.model.BoletoAlteracaoProrrogacaoVencimento;
import br.com.sicoob.cobrancav3.model.BoletoAlteracaoRateioCredito;
import br.com.sicoob.cobrancav3.model.BoletoAlteracaoSeuNumero;
import br.com.sicoob.cobrancav3.model.BoletoAlteracaoValorNominal;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import br.com.sicoob.cobrancav3.JSON;

/**
 * BoletoAlteracao
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-05-04T12:32:46.205909-03:00[America/Sao_Paulo]", comments = "Generator version: 7.22.0")
public class BoletoAlteracao {
  public static final String SERIALIZED_NAME_NUMERO_CLIENTE = "numeroCliente";
  @SerializedName(SERIALIZED_NAME_NUMERO_CLIENTE)
  @javax.annotation.Nonnull
  private Long numeroCliente;

  public static final String SERIALIZED_NAME_CODIGO_MODALIDADE = "codigoModalidade";
  @SerializedName(SERIALIZED_NAME_CODIGO_MODALIDADE)
  @javax.annotation.Nonnull
  private Integer codigoModalidade;

  public static final String SERIALIZED_NAME_NUMERO_CONTRATO_COBRANCA = "numeroContratoCobranca";
  @SerializedName(SERIALIZED_NAME_NUMERO_CONTRATO_COBRANCA)
  @javax.annotation.Nullable
  private Long numeroContratoCobranca;

  public static final String SERIALIZED_NAME_ESPECIE_DOCUMENTO = "especieDocumento";
  @SerializedName(SERIALIZED_NAME_ESPECIE_DOCUMENTO)
  @javax.annotation.Nullable
  private BoletoAlteracaoEspecieDocumento especieDocumento;

  public static final String SERIALIZED_NAME_SEU_NUMERO = "seuNumero";
  @SerializedName(SERIALIZED_NAME_SEU_NUMERO)
  @javax.annotation.Nullable
  private BoletoAlteracaoSeuNumero seuNumero;

  public static final String SERIALIZED_NAME_DESCONTO = "desconto";
  @SerializedName(SERIALIZED_NAME_DESCONTO)
  @javax.annotation.Nullable
  private BoletoAlteracaoDesconto desconto;

  public static final String SERIALIZED_NAME_ABATIMENTO = "abatimento";
  @SerializedName(SERIALIZED_NAME_ABATIMENTO)
  @javax.annotation.Nullable
  private BoletoAlteracaoAbatimento abatimento;

  public static final String SERIALIZED_NAME_MULTA = "multa";
  @SerializedName(SERIALIZED_NAME_MULTA)
  @javax.annotation.Nullable
  private BoletoAlteracaoMulta multa;

  public static final String SERIALIZED_NAME_JUROS_MORA = "jurosMora";
  @SerializedName(SERIALIZED_NAME_JUROS_MORA)
  @javax.annotation.Nullable
  private BoletoAlteracaoJurosMora jurosMora;

  public static final String SERIALIZED_NAME_RATEIO_CREDITO = "rateioCredito";
  @SerializedName(SERIALIZED_NAME_RATEIO_CREDITO)
  @javax.annotation.Nullable
  private BoletoAlteracaoRateioCredito rateioCredito;

  public static final String SERIALIZED_NAME_PIX = "pix";
  @SerializedName(SERIALIZED_NAME_PIX)
  @javax.annotation.Nullable
  private BoletoAlteracaoPix pix;

  public static final String SERIALIZED_NAME_PRORROGACAO_VENCIMENTO = "prorrogacaoVencimento";
  @SerializedName(SERIALIZED_NAME_PRORROGACAO_VENCIMENTO)
  @javax.annotation.Nullable
  private BoletoAlteracaoProrrogacaoVencimento prorrogacaoVencimento;

  public static final String SERIALIZED_NAME_PRORROGACAO_LIMITE_PAGAMENTO = "prorrogacaoLimitePagamento";
  @SerializedName(SERIALIZED_NAME_PRORROGACAO_LIMITE_PAGAMENTO)
  @javax.annotation.Nullable
  private BoletoAlteracaoProrrogacaoLimitePagamento prorrogacaoLimitePagamento;

  public static final String SERIALIZED_NAME_VALOR_NOMINAL = "valorNominal";
  @SerializedName(SERIALIZED_NAME_VALOR_NOMINAL)
  @javax.annotation.Nullable
  private BoletoAlteracaoValorNominal valorNominal;

  public BoletoAlteracao() {
  }

  public BoletoAlteracao numeroCliente(@javax.annotation.Nonnull Long numeroCliente) {
    this.numeroCliente = numeroCliente;
    return this;
  }

  /**
   * Número que identifica o contrato do beneficiário no Sisbr.
   * @return numeroCliente
   */
  @javax.annotation.Nonnull
  public Long getNumeroCliente() {
    return numeroCliente;
  }

  public void setNumeroCliente(@javax.annotation.Nonnull Long numeroCliente) {
    this.numeroCliente = numeroCliente;
  }


  public BoletoAlteracao codigoModalidade(@javax.annotation.Nonnull Integer codigoModalidade) {
    this.codigoModalidade = codigoModalidade;
    return this;
  }

  /**
   * Número que identifica a modalidade do boleto. - 1 - SIMPLES COM REGISTRO - 3 - CAUCIONADA - 4 - VINCULADA - 5 - CARNÊ DE PAGAMENTOS - 8 - COBRANÇA CONTA CAPITAL
   * @return codigoModalidade
   */
  @javax.annotation.Nonnull
  public Integer getCodigoModalidade() {
    return codigoModalidade;
  }

  public void setCodigoModalidade(@javax.annotation.Nonnull Integer codigoModalidade) {
    this.codigoModalidade = codigoModalidade;
  }


  public BoletoAlteracao numeroContratoCobranca(@javax.annotation.Nullable Long numeroContratoCobranca) {
    this.numeroContratoCobranca = numeroContratoCobranca;
    return this;
  }

  /**
   * Indicar o id do contatroCobranca
   * @return numeroContratoCobranca
   */
  @javax.annotation.Nullable
  public Long getNumeroContratoCobranca() {
    return numeroContratoCobranca;
  }

  public void setNumeroContratoCobranca(@javax.annotation.Nullable Long numeroContratoCobranca) {
    this.numeroContratoCobranca = numeroContratoCobranca;
  }


  public BoletoAlteracao especieDocumento(@javax.annotation.Nullable BoletoAlteracaoEspecieDocumento especieDocumento) {
    this.especieDocumento = especieDocumento;
    return this;
  }

  /**
   * Get especieDocumento
   * @return especieDocumento
   */
  @javax.annotation.Nullable
  public BoletoAlteracaoEspecieDocumento getEspecieDocumento() {
    return especieDocumento;
  }

  public void setEspecieDocumento(@javax.annotation.Nullable BoletoAlteracaoEspecieDocumento especieDocumento) {
    this.especieDocumento = especieDocumento;
  }


  public BoletoAlteracao seuNumero(@javax.annotation.Nullable BoletoAlteracaoSeuNumero seuNumero) {
    this.seuNumero = seuNumero;
    return this;
  }

  /**
   * Get seuNumero
   * @return seuNumero
   */
  @javax.annotation.Nullable
  public BoletoAlteracaoSeuNumero getSeuNumero() {
    return seuNumero;
  }

  public void setSeuNumero(@javax.annotation.Nullable BoletoAlteracaoSeuNumero seuNumero) {
    this.seuNumero = seuNumero;
  }


  public BoletoAlteracao desconto(@javax.annotation.Nullable BoletoAlteracaoDesconto desconto) {
    this.desconto = desconto;
    return this;
  }

  /**
   * Get desconto
   * @return desconto
   */
  @javax.annotation.Nullable
  public BoletoAlteracaoDesconto getDesconto() {
    return desconto;
  }

  public void setDesconto(@javax.annotation.Nullable BoletoAlteracaoDesconto desconto) {
    this.desconto = desconto;
  }


  public BoletoAlteracao abatimento(@javax.annotation.Nullable BoletoAlteracaoAbatimento abatimento) {
    this.abatimento = abatimento;
    return this;
  }

  /**
   * Get abatimento
   * @return abatimento
   */
  @javax.annotation.Nullable
  public BoletoAlteracaoAbatimento getAbatimento() {
    return abatimento;
  }

  public void setAbatimento(@javax.annotation.Nullable BoletoAlteracaoAbatimento abatimento) {
    this.abatimento = abatimento;
  }


  public BoletoAlteracao multa(@javax.annotation.Nullable BoletoAlteracaoMulta multa) {
    this.multa = multa;
    return this;
  }

  /**
   * Get multa
   * @return multa
   */
  @javax.annotation.Nullable
  public BoletoAlteracaoMulta getMulta() {
    return multa;
  }

  public void setMulta(@javax.annotation.Nullable BoletoAlteracaoMulta multa) {
    this.multa = multa;
  }


  public BoletoAlteracao jurosMora(@javax.annotation.Nullable BoletoAlteracaoJurosMora jurosMora) {
    this.jurosMora = jurosMora;
    return this;
  }

  /**
   * Get jurosMora
   * @return jurosMora
   */
  @javax.annotation.Nullable
  public BoletoAlteracaoJurosMora getJurosMora() {
    return jurosMora;
  }

  public void setJurosMora(@javax.annotation.Nullable BoletoAlteracaoJurosMora jurosMora) {
    this.jurosMora = jurosMora;
  }


  public BoletoAlteracao rateioCredito(@javax.annotation.Nullable BoletoAlteracaoRateioCredito rateioCredito) {
    this.rateioCredito = rateioCredito;
    return this;
  }

  /**
   * Get rateioCredito
   * @return rateioCredito
   */
  @javax.annotation.Nullable
  public BoletoAlteracaoRateioCredito getRateioCredito() {
    return rateioCredito;
  }

  public void setRateioCredito(@javax.annotation.Nullable BoletoAlteracaoRateioCredito rateioCredito) {
    this.rateioCredito = rateioCredito;
  }


  public BoletoAlteracao pix(@javax.annotation.Nullable BoletoAlteracaoPix pix) {
    this.pix = pix;
    return this;
  }

  /**
   * Get pix
   * @return pix
   */
  @javax.annotation.Nullable
  public BoletoAlteracaoPix getPix() {
    return pix;
  }

  public void setPix(@javax.annotation.Nullable BoletoAlteracaoPix pix) {
    this.pix = pix;
  }


  public BoletoAlteracao prorrogacaoVencimento(@javax.annotation.Nullable BoletoAlteracaoProrrogacaoVencimento prorrogacaoVencimento) {
    this.prorrogacaoVencimento = prorrogacaoVencimento;
    return this;
  }

  /**
   * Get prorrogacaoVencimento
   * @return prorrogacaoVencimento
   */
  @javax.annotation.Nullable
  public BoletoAlteracaoProrrogacaoVencimento getProrrogacaoVencimento() {
    return prorrogacaoVencimento;
  }

  public void setProrrogacaoVencimento(@javax.annotation.Nullable BoletoAlteracaoProrrogacaoVencimento prorrogacaoVencimento) {
    this.prorrogacaoVencimento = prorrogacaoVencimento;
  }


  public BoletoAlteracao prorrogacaoLimitePagamento(@javax.annotation.Nullable BoletoAlteracaoProrrogacaoLimitePagamento prorrogacaoLimitePagamento) {
    this.prorrogacaoLimitePagamento = prorrogacaoLimitePagamento;
    return this;
  }

  /**
   * Get prorrogacaoLimitePagamento
   * @return prorrogacaoLimitePagamento
   */
  @javax.annotation.Nullable
  public BoletoAlteracaoProrrogacaoLimitePagamento getProrrogacaoLimitePagamento() {
    return prorrogacaoLimitePagamento;
  }

  public void setProrrogacaoLimitePagamento(@javax.annotation.Nullable BoletoAlteracaoProrrogacaoLimitePagamento prorrogacaoLimitePagamento) {
    this.prorrogacaoLimitePagamento = prorrogacaoLimitePagamento;
  }


  public BoletoAlteracao valorNominal(@javax.annotation.Nullable BoletoAlteracaoValorNominal valorNominal) {
    this.valorNominal = valorNominal;
    return this;
  }

  /**
   * Get valorNominal
   * @return valorNominal
   */
  @javax.annotation.Nullable
  public BoletoAlteracaoValorNominal getValorNominal() {
    return valorNominal;
  }

  public void setValorNominal(@javax.annotation.Nullable BoletoAlteracaoValorNominal valorNominal) {
    this.valorNominal = valorNominal;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BoletoAlteracao boletoAlteracao = (BoletoAlteracao) o;
    return Objects.equals(this.numeroCliente, boletoAlteracao.numeroCliente) &&
        Objects.equals(this.codigoModalidade, boletoAlteracao.codigoModalidade) &&
        Objects.equals(this.numeroContratoCobranca, boletoAlteracao.numeroContratoCobranca) &&
        Objects.equals(this.especieDocumento, boletoAlteracao.especieDocumento) &&
        Objects.equals(this.seuNumero, boletoAlteracao.seuNumero) &&
        Objects.equals(this.desconto, boletoAlteracao.desconto) &&
        Objects.equals(this.abatimento, boletoAlteracao.abatimento) &&
        Objects.equals(this.multa, boletoAlteracao.multa) &&
        Objects.equals(this.jurosMora, boletoAlteracao.jurosMora) &&
        Objects.equals(this.rateioCredito, boletoAlteracao.rateioCredito) &&
        Objects.equals(this.pix, boletoAlteracao.pix) &&
        Objects.equals(this.prorrogacaoVencimento, boletoAlteracao.prorrogacaoVencimento) &&
        Objects.equals(this.prorrogacaoLimitePagamento, boletoAlteracao.prorrogacaoLimitePagamento) &&
        Objects.equals(this.valorNominal, boletoAlteracao.valorNominal);
  }

  @Override
  public int hashCode() {
    return Objects.hash(numeroCliente, codigoModalidade, numeroContratoCobranca, especieDocumento, seuNumero, desconto, abatimento, multa, jurosMora, rateioCredito, pix, prorrogacaoVencimento, prorrogacaoLimitePagamento, valorNominal);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BoletoAlteracao {\n");
    sb.append("    numeroCliente: ").append(toIndentedString(numeroCliente)).append("\n");
    sb.append("    codigoModalidade: ").append(toIndentedString(codigoModalidade)).append("\n");
    sb.append("    numeroContratoCobranca: ").append(toIndentedString(numeroContratoCobranca)).append("\n");
    sb.append("    especieDocumento: ").append(toIndentedString(especieDocumento)).append("\n");
    sb.append("    seuNumero: ").append(toIndentedString(seuNumero)).append("\n");
    sb.append("    desconto: ").append(toIndentedString(desconto)).append("\n");
    sb.append("    abatimento: ").append(toIndentedString(abatimento)).append("\n");
    sb.append("    multa: ").append(toIndentedString(multa)).append("\n");
    sb.append("    jurosMora: ").append(toIndentedString(jurosMora)).append("\n");
    sb.append("    rateioCredito: ").append(toIndentedString(rateioCredito)).append("\n");
    sb.append("    pix: ").append(toIndentedString(pix)).append("\n");
    sb.append("    prorrogacaoVencimento: ").append(toIndentedString(prorrogacaoVencimento)).append("\n");
    sb.append("    prorrogacaoLimitePagamento: ").append(toIndentedString(prorrogacaoLimitePagamento)).append("\n");
    sb.append("    valorNominal: ").append(toIndentedString(valorNominal)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("numeroCliente", "codigoModalidade", "numeroContratoCobranca", "especieDocumento", "seuNumero", "desconto", "abatimento", "multa", "jurosMora", "rateioCredito", "pix", "prorrogacaoVencimento", "prorrogacaoLimitePagamento", "valorNominal"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("numeroCliente", "codigoModalidade"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to BoletoAlteracao
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!BoletoAlteracao.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in BoletoAlteracao is not found in the empty JSON string", BoletoAlteracao.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!BoletoAlteracao.openapiFields.contains(entry.getKey())) {
          // throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `BoletoAlteracao` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : BoletoAlteracao.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `especieDocumento`
      if (jsonObj.get("especieDocumento") != null && !jsonObj.get("especieDocumento").isJsonNull()) {
        BoletoAlteracaoEspecieDocumento.validateJsonElement(jsonObj.get("especieDocumento"));
      }
      // validate the optional field `seuNumero`
      if (jsonObj.get("seuNumero") != null && !jsonObj.get("seuNumero").isJsonNull()) {
        BoletoAlteracaoSeuNumero.validateJsonElement(jsonObj.get("seuNumero"));
      }
      // validate the optional field `desconto`
      if (jsonObj.get("desconto") != null && !jsonObj.get("desconto").isJsonNull()) {
        BoletoAlteracaoDesconto.validateJsonElement(jsonObj.get("desconto"));
      }
      // validate the optional field `abatimento`
      if (jsonObj.get("abatimento") != null && !jsonObj.get("abatimento").isJsonNull()) {
        BoletoAlteracaoAbatimento.validateJsonElement(jsonObj.get("abatimento"));
      }
      // validate the optional field `multa`
      if (jsonObj.get("multa") != null && !jsonObj.get("multa").isJsonNull()) {
        BoletoAlteracaoMulta.validateJsonElement(jsonObj.get("multa"));
      }
      // validate the optional field `jurosMora`
      if (jsonObj.get("jurosMora") != null && !jsonObj.get("jurosMora").isJsonNull()) {
        BoletoAlteracaoJurosMora.validateJsonElement(jsonObj.get("jurosMora"));
      }
      // validate the optional field `rateioCredito`
      if (jsonObj.get("rateioCredito") != null && !jsonObj.get("rateioCredito").isJsonNull()) {
        BoletoAlteracaoRateioCredito.validateJsonElement(jsonObj.get("rateioCredito"));
      }
      // validate the optional field `pix`
      if (jsonObj.get("pix") != null && !jsonObj.get("pix").isJsonNull()) {
        BoletoAlteracaoPix.validateJsonElement(jsonObj.get("pix"));
      }
      // validate the optional field `prorrogacaoVencimento`
      if (jsonObj.get("prorrogacaoVencimento") != null && !jsonObj.get("prorrogacaoVencimento").isJsonNull()) {
        BoletoAlteracaoProrrogacaoVencimento.validateJsonElement(jsonObj.get("prorrogacaoVencimento"));
      }
      // validate the optional field `prorrogacaoLimitePagamento`
      if (jsonObj.get("prorrogacaoLimitePagamento") != null && !jsonObj.get("prorrogacaoLimitePagamento").isJsonNull()) {
        BoletoAlteracaoProrrogacaoLimitePagamento.validateJsonElement(jsonObj.get("prorrogacaoLimitePagamento"));
      }
      // validate the optional field `valorNominal`
      if (jsonObj.get("valorNominal") != null && !jsonObj.get("valorNominal").isJsonNull()) {
        BoletoAlteracaoValorNominal.validateJsonElement(jsonObj.get("valorNominal"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!BoletoAlteracao.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'BoletoAlteracao' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<BoletoAlteracao> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(BoletoAlteracao.class));

       return (TypeAdapter<T>) new TypeAdapter<BoletoAlteracao>() {
           @Override
           public void write(JsonWriter out, BoletoAlteracao value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public BoletoAlteracao read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of BoletoAlteracao given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of BoletoAlteracao
   * @throws IOException if the JSON string is invalid with respect to BoletoAlteracao
   */
  public static BoletoAlteracao fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, BoletoAlteracao.class);
  }

  /**
   * Convert an instance of BoletoAlteracao to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

