/*
 * Cobrança Bancária
 * <pre>[ Base URL: https://api.sicoob.com.br/cobranca-bancaria/v3 ]</pre> A Cobrança Bancária Sicoob é um conjunto de serviços oferecidos a seus associados para recebimento de valores referentes às vendas de produtos e serviços da sua empresa, por meio de boletos de cobrança, pagos em toda a rede bancária. Esta API disponibiliza funcionalidades que auxiliam na gestão da carteira registrada, tornando viável todo o processo de acompanhamento, desde a inclusão de novos boletos, alteração de informações relevantes, protesto/negativação de títulos vencidos e não pagos, até a liquidação ou baixa do título.
 *
 * The version of the OpenAPI document: 3.0.8.0
 * Contact: GrupoGesin1CobrancaBancaria@sicoob.com.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.sicoob.cobrancav3.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import br.com.sicoob.cobrancav3.JSON;

/**
 * BoletosMovimentacoesGet200ResponseResultado
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-05-04T12:32:46.205909-03:00[America/Sao_Paulo]", comments = "Generator version: 7.22.0")
public class BoletosMovimentacoesGet200ResponseResultado {
  public static final String SERIALIZED_NAME_QUANTIDADE_TOTAL_REGISTROS = "quantidadeTotalRegistros";
  @SerializedName(SERIALIZED_NAME_QUANTIDADE_TOTAL_REGISTROS)
  @javax.annotation.Nonnull
  private Integer quantidadeTotalRegistros;

  public static final String SERIALIZED_NAME_QUANTIDADE_REGISTROS_ARQUIVO = "quantidadeRegistrosArquivo";
  @SerializedName(SERIALIZED_NAME_QUANTIDADE_REGISTROS_ARQUIVO)
  @javax.annotation.Nullable
  private Integer quantidadeRegistrosArquivo;

  public static final String SERIALIZED_NAME_QUANTIDADE_ARQUIVO = "quantidadeArquivo";
  @SerializedName(SERIALIZED_NAME_QUANTIDADE_ARQUIVO)
  @javax.annotation.Nonnull
  private Integer quantidadeArquivo;

  public static final String SERIALIZED_NAME_ID_ARQUIVOS = "idArquivos";
  @SerializedName(SERIALIZED_NAME_ID_ARQUIVOS)
  @javax.annotation.Nonnull
  private List<Integer> idArquivos = new ArrayList<>();

  public BoletosMovimentacoesGet200ResponseResultado() {
  }

  public BoletosMovimentacoesGet200ResponseResultado quantidadeTotalRegistros(@javax.annotation.Nonnull Integer quantidadeTotalRegistros) {
    this.quantidadeTotalRegistros = quantidadeTotalRegistros;
    return this;
  }

  /**
   * Quantidade Total de Registos encontrados para a movimentação solicitada.
   * @return quantidadeTotalRegistros
   */
  @javax.annotation.Nonnull
  public Integer getQuantidadeTotalRegistros() {
    return quantidadeTotalRegistros;
  }

  public void setQuantidadeTotalRegistros(@javax.annotation.Nonnull Integer quantidadeTotalRegistros) {
    this.quantidadeTotalRegistros = quantidadeTotalRegistros;
  }


  public BoletosMovimentacoesGet200ResponseResultado quantidadeRegistrosArquivo(@javax.annotation.Nullable Integer quantidadeRegistrosArquivo) {
    this.quantidadeRegistrosArquivo = quantidadeRegistrosArquivo;
    return this;
  }

  /**
   * Quantidade Máxima de registos por arquivo.
   * @return quantidadeRegistrosArquivo
   */
  @javax.annotation.Nullable
  public Integer getQuantidadeRegistrosArquivo() {
    return quantidadeRegistrosArquivo;
  }

  public void setQuantidadeRegistrosArquivo(@javax.annotation.Nullable Integer quantidadeRegistrosArquivo) {
    this.quantidadeRegistrosArquivo = quantidadeRegistrosArquivo;
  }


  public BoletosMovimentacoesGet200ResponseResultado quantidadeArquivo(@javax.annotation.Nonnull Integer quantidadeArquivo) {
    this.quantidadeArquivo = quantidadeArquivo;
    return this;
  }

  /**
   * Quantidade de arquivo(s) da movimentação retornada na consulta.
   * @return quantidadeArquivo
   */
  @javax.annotation.Nonnull
  public Integer getQuantidadeArquivo() {
    return quantidadeArquivo;
  }

  public void setQuantidadeArquivo(@javax.annotation.Nonnull Integer quantidadeArquivo) {
    this.quantidadeArquivo = quantidadeArquivo;
  }


  public BoletosMovimentacoesGet200ResponseResultado idArquivos(@javax.annotation.Nonnull List<Integer> idArquivos) {
    this.idArquivos = idArquivos;
    return this;
  }

  public BoletosMovimentacoesGet200ResponseResultado addIdArquivosItem(Integer idArquivosItem) {
    if (this.idArquivos == null) {
      this.idArquivos = new ArrayList<>();
    }
    this.idArquivos.add(idArquivosItem);
    return this;
  }

  /**
   * Get idArquivos
   * @return idArquivos
   */
  @javax.annotation.Nonnull
  public List<Integer> getIdArquivos() {
    return idArquivos;
  }

  public void setIdArquivos(@javax.annotation.Nonnull List<Integer> idArquivos) {
    this.idArquivos = idArquivos;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BoletosMovimentacoesGet200ResponseResultado boletosMovimentacoesGet200ResponseResultado = (BoletosMovimentacoesGet200ResponseResultado) o;
    return Objects.equals(this.quantidadeTotalRegistros, boletosMovimentacoesGet200ResponseResultado.quantidadeTotalRegistros) &&
        Objects.equals(this.quantidadeRegistrosArquivo, boletosMovimentacoesGet200ResponseResultado.quantidadeRegistrosArquivo) &&
        Objects.equals(this.quantidadeArquivo, boletosMovimentacoesGet200ResponseResultado.quantidadeArquivo) &&
        Objects.equals(this.idArquivos, boletosMovimentacoesGet200ResponseResultado.idArquivos);
  }

  @Override
  public int hashCode() {
    return Objects.hash(quantidadeTotalRegistros, quantidadeRegistrosArquivo, quantidadeArquivo, idArquivos);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BoletosMovimentacoesGet200ResponseResultado {\n");
    sb.append("    quantidadeTotalRegistros: ").append(toIndentedString(quantidadeTotalRegistros)).append("\n");
    sb.append("    quantidadeRegistrosArquivo: ").append(toIndentedString(quantidadeRegistrosArquivo)).append("\n");
    sb.append("    quantidadeArquivo: ").append(toIndentedString(quantidadeArquivo)).append("\n");
    sb.append("    idArquivos: ").append(toIndentedString(idArquivos)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("quantidadeTotalRegistros", "quantidadeRegistrosArquivo", "quantidadeArquivo", "idArquivos"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("quantidadeTotalRegistros", "quantidadeArquivo", "idArquivos"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to BoletosMovimentacoesGet200ResponseResultado
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!BoletosMovimentacoesGet200ResponseResultado.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in BoletosMovimentacoesGet200ResponseResultado is not found in the empty JSON string", BoletosMovimentacoesGet200ResponseResultado.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!BoletosMovimentacoesGet200ResponseResultado.openapiFields.contains(entry.getKey())) {
          // throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `BoletosMovimentacoesGet200ResponseResultado` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : BoletosMovimentacoesGet200ResponseResultado.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the required json array is present
      if (jsonObj.get("idArquivos") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("idArquivos").isJsonArray()) {
        // throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `idArquivos` to be an array in the JSON string but got `%s`", jsonObj.get("idArquivos").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!BoletosMovimentacoesGet200ResponseResultado.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'BoletosMovimentacoesGet200ResponseResultado' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<BoletosMovimentacoesGet200ResponseResultado> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(BoletosMovimentacoesGet200ResponseResultado.class));

       return (TypeAdapter<T>) new TypeAdapter<BoletosMovimentacoesGet200ResponseResultado>() {
           @Override
           public void write(JsonWriter out, BoletosMovimentacoesGet200ResponseResultado value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public BoletosMovimentacoesGet200ResponseResultado read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of BoletosMovimentacoesGet200ResponseResultado given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of BoletosMovimentacoesGet200ResponseResultado
   * @throws IOException if the JSON string is invalid with respect to BoletosMovimentacoesGet200ResponseResultado
   */
  public static BoletosMovimentacoesGet200ResponseResultado fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, BoletosMovimentacoesGet200ResponseResultado.class);
  }

  /**
   * Convert an instance of BoletosMovimentacoesGet200ResponseResultado to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

