/*
 * Cobrança Bancária
 * <pre>[ Base URL: https://api.sicoob.com.br/cobranca-bancaria/v3 ]</pre> A Cobrança Bancária Sicoob é um conjunto de serviços oferecidos a seus associados para recebimento de valores referentes às vendas de produtos e serviços da sua empresa, por meio de boletos de cobrança, pagos em toda a rede bancária. Esta API disponibiliza funcionalidades que auxiliam na gestão da carteira registrada, tornando viável todo o processo de acompanhamento, desde a inclusão de novos boletos, alteração de informações relevantes, protesto/negativação de títulos vencidos e não pagos, até a liquidação ou baixa do título.
 *
 * The version of the OpenAPI document: 3.0.8.0
 * Contact: GrupoGesin1CobrancaBancaria@sicoob.com.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.sicoob.cobrancav3.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.LocalDate;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import br.com.sicoob.cobrancav3.JSON;

/**
 * BoletoAlteracaoJurosMora
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-05-04T12:32:46.205909-03:00[America/Sao_Paulo]", comments = "Generator version: 7.22.0")
public class BoletoAlteracaoJurosMora {
  public static final String SERIALIZED_NAME_TIPO_JUROS_MORA = "tipoJurosMora";
  @SerializedName(SERIALIZED_NAME_TIPO_JUROS_MORA)
  @javax.annotation.Nonnull
  private Integer tipoJurosMora;

  public static final String SERIALIZED_NAME_DATA_JUROS_MORA = "dataJurosMora";
  @SerializedName(SERIALIZED_NAME_DATA_JUROS_MORA)
  @javax.annotation.Nullable
  private LocalDate dataJurosMora;

  public static final String SERIALIZED_NAME_VALOR_JUROS_MORA = "valorJurosMora";
  @SerializedName(SERIALIZED_NAME_VALOR_JUROS_MORA)
  @javax.annotation.Nullable
  private Double valorJurosMora;

  public BoletoAlteracaoJurosMora() {
  }

  public BoletoAlteracaoJurosMora tipoJurosMora(@javax.annotation.Nonnull Integer tipoJurosMora) {
    this.tipoJurosMora = tipoJurosMora;
    return this;
  }

  /**
   * Tipo de Juros de Mora   - 1 Valor por dia   - 2 Taxa Mensal   - 3 Isento
   * @return tipoJurosMora
   */
  @javax.annotation.Nonnull
  public Integer getTipoJurosMora() {
    return tipoJurosMora;
  }

  public void setTipoJurosMora(@javax.annotation.Nonnull Integer tipoJurosMora) {
    this.tipoJurosMora = tipoJurosMora;
  }


  public BoletoAlteracaoJurosMora dataJurosMora(@javax.annotation.Nullable LocalDate dataJurosMora) {
    this.dataJurosMora = dataJurosMora;
    return this;
  }

  /**
   * Deve ser maior que a data de vencimento do boleto e menor ou igual que data limite de pagamento.
   * @return dataJurosMora
   */
  @javax.annotation.Nullable
  public LocalDate getDataJurosMora() {
    return dataJurosMora;
  }

  public void setDataJurosMora(@javax.annotation.Nullable LocalDate dataJurosMora) {
    this.dataJurosMora = dataJurosMora;
  }


  public BoletoAlteracaoJurosMora valorJurosMora(@javax.annotation.Nullable Double valorJurosMora) {
    this.valorJurosMora = valorJurosMora;
    return this;
  }

  /**
   * Valor do Juros de Mora.
   * @return valorJurosMora
   */
  @javax.annotation.Nullable
  public Double getValorJurosMora() {
    return valorJurosMora;
  }

  public void setValorJurosMora(@javax.annotation.Nullable Double valorJurosMora) {
    this.valorJurosMora = valorJurosMora;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BoletoAlteracaoJurosMora boletoAlteracaoJurosMora = (BoletoAlteracaoJurosMora) o;
    return Objects.equals(this.tipoJurosMora, boletoAlteracaoJurosMora.tipoJurosMora) &&
        Objects.equals(this.dataJurosMora, boletoAlteracaoJurosMora.dataJurosMora) &&
        Objects.equals(this.valorJurosMora, boletoAlteracaoJurosMora.valorJurosMora);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tipoJurosMora, dataJurosMora, valorJurosMora);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BoletoAlteracaoJurosMora {\n");
    sb.append("    tipoJurosMora: ").append(toIndentedString(tipoJurosMora)).append("\n");
    sb.append("    dataJurosMora: ").append(toIndentedString(dataJurosMora)).append("\n");
    sb.append("    valorJurosMora: ").append(toIndentedString(valorJurosMora)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("tipoJurosMora", "dataJurosMora", "valorJurosMora"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("tipoJurosMora"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to BoletoAlteracaoJurosMora
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!BoletoAlteracaoJurosMora.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in BoletoAlteracaoJurosMora is not found in the empty JSON string", BoletoAlteracaoJurosMora.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!BoletoAlteracaoJurosMora.openapiFields.contains(entry.getKey())) {
          // throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `BoletoAlteracaoJurosMora` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : BoletoAlteracaoJurosMora.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!BoletoAlteracaoJurosMora.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'BoletoAlteracaoJurosMora' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<BoletoAlteracaoJurosMora> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(BoletoAlteracaoJurosMora.class));

       return (TypeAdapter<T>) new TypeAdapter<BoletoAlteracaoJurosMora>() {
           @Override
           public void write(JsonWriter out, BoletoAlteracaoJurosMora value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public BoletoAlteracaoJurosMora read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of BoletoAlteracaoJurosMora given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of BoletoAlteracaoJurosMora
   * @throws IOException if the JSON string is invalid with respect to BoletoAlteracaoJurosMora
   */
  public static BoletoAlteracaoJurosMora fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, BoletoAlteracaoJurosMora.class);
  }

  /**
   * Convert an instance of BoletoAlteracaoJurosMora to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

