/*
 * Cobrança Bancária
 * <pre>[ Base URL: https://api.sicoob.com.br/cobranca-bancaria/v3 ]</pre> A Cobrança Bancária Sicoob é um conjunto de serviços oferecidos a seus associados para recebimento de valores referentes às vendas de produtos e serviços da sua empresa, por meio de boletos de cobrança, pagos em toda a rede bancária. Esta API disponibiliza funcionalidades que auxiliam na gestão da carteira registrada, tornando viável todo o processo de acompanhamento, desde a inclusão de novos boletos, alteração de informações relevantes, protesto/negativação de títulos vencidos e não pagos, até a liquidação ou baixa do título.
 *
 * The version of the OpenAPI document: 3.0.8.0
 * Contact: GrupoGesin1CobrancaBancaria@sicoob.com.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.sicoob.cobrancav3.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import br.com.sicoob.cobrancav3.JSON;

/**
 * FaixaNossoNumero
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-05-04T12:32:46.205909-03:00[America/Sao_Paulo]", comments = "Generator version: 7.22.0")
public class FaixaNossoNumero {
  public static final String SERIALIZED_NAME_NUMERO_CLIENTE = "numeroCliente";
  @SerializedName(SERIALIZED_NAME_NUMERO_CLIENTE)
  @javax.annotation.Nonnull
  private Integer numeroCliente;

  public static final String SERIALIZED_NAME_NOME_CLIENTE = "nomeCliente";
  @SerializedName(SERIALIZED_NAME_NOME_CLIENTE)
  @javax.annotation.Nonnull
  private String nomeCliente;

  public static final String SERIALIZED_NAME_NUMERO_INICIAL = "numeroInicial";
  @SerializedName(SERIALIZED_NAME_NUMERO_INICIAL)
  @javax.annotation.Nonnull
  private Integer numeroInicial;

  public static final String SERIALIZED_NAME_NUMERO_FINAL = "numeroFinal";
  @SerializedName(SERIALIZED_NAME_NUMERO_FINAL)
  @javax.annotation.Nonnull
  private Integer numeroFinal;

  public static final String SERIALIZED_NAME_QUANTIDADE = "quantidade";
  @SerializedName(SERIALIZED_NAME_QUANTIDADE)
  @javax.annotation.Nonnull
  private Integer quantidade;

  public static final String SERIALIZED_NAME_NUMERO_CONTRATO_COBRANCA = "numeroContratoCobranca";
  @SerializedName(SERIALIZED_NAME_NUMERO_CONTRATO_COBRANCA)
  @javax.annotation.Nullable
  private Long numeroContratoCobranca;

  public static final String SERIALIZED_NAME_VALIDA_DIGITO_VERIFICADOR_NOSSO_NUMERO = "validaDigitoVerificadorNossoNumero";
  @SerializedName(SERIALIZED_NAME_VALIDA_DIGITO_VERIFICADOR_NOSSO_NUMERO)
  @javax.annotation.Nonnull
  private Boolean validaDigitoVerificadorNossoNumero;

  public FaixaNossoNumero() {
  }

  public FaixaNossoNumero numeroCliente(@javax.annotation.Nonnull Integer numeroCliente) {
    this.numeroCliente = numeroCliente;
    return this;
  }

  /**
   * Número do contrato
   * @return numeroCliente
   */
  @javax.annotation.Nonnull
  public Integer getNumeroCliente() {
    return numeroCliente;
  }

  public void setNumeroCliente(@javax.annotation.Nonnull Integer numeroCliente) {
    this.numeroCliente = numeroCliente;
  }


  public FaixaNossoNumero nomeCliente(@javax.annotation.Nonnull String nomeCliente) {
    this.nomeCliente = nomeCliente;
    return this;
  }

  /**
   * Nome do cliente
   * @return nomeCliente
   */
  @javax.annotation.Nonnull
  public String getNomeCliente() {
    return nomeCliente;
  }

  public void setNomeCliente(@javax.annotation.Nonnull String nomeCliente) {
    this.nomeCliente = nomeCliente;
  }


  public FaixaNossoNumero numeroInicial(@javax.annotation.Nonnull Integer numeroInicial) {
    this.numeroInicial = numeroInicial;
    return this;
  }

  /**
   * Número do início da faixa
   * @return numeroInicial
   */
  @javax.annotation.Nonnull
  public Integer getNumeroInicial() {
    return numeroInicial;
  }

  public void setNumeroInicial(@javax.annotation.Nonnull Integer numeroInicial) {
    this.numeroInicial = numeroInicial;
  }


  public FaixaNossoNumero numeroFinal(@javax.annotation.Nonnull Integer numeroFinal) {
    this.numeroFinal = numeroFinal;
    return this;
  }

  /**
   * Número do final da faixa
   * @return numeroFinal
   */
  @javax.annotation.Nonnull
  public Integer getNumeroFinal() {
    return numeroFinal;
  }

  public void setNumeroFinal(@javax.annotation.Nonnull Integer numeroFinal) {
    this.numeroFinal = numeroFinal;
  }


  public FaixaNossoNumero quantidade(@javax.annotation.Nonnull Integer quantidade) {
    this.quantidade = quantidade;
    return this;
  }

  /**
   * Quantidade
   * @return quantidade
   */
  @javax.annotation.Nonnull
  public Integer getQuantidade() {
    return quantidade;
  }

  public void setQuantidade(@javax.annotation.Nonnull Integer quantidade) {
    this.quantidade = quantidade;
  }


  public FaixaNossoNumero numeroContratoCobranca(@javax.annotation.Nullable Long numeroContratoCobranca) {
    this.numeroContratoCobranca = numeroContratoCobranca;
    return this;
  }

  /**
   * Indicar o id do contatroCobranca
   * @return numeroContratoCobranca
   */
  @javax.annotation.Nullable
  public Long getNumeroContratoCobranca() {
    return numeroContratoCobranca;
  }

  public void setNumeroContratoCobranca(@javax.annotation.Nullable Long numeroContratoCobranca) {
    this.numeroContratoCobranca = numeroContratoCobranca;
  }


  public FaixaNossoNumero validaDigitoVerificadorNossoNumero(@javax.annotation.Nonnull Boolean validaDigitoVerificadorNossoNumero) {
    this.validaDigitoVerificadorNossoNumero = validaDigitoVerificadorNossoNumero;
    return this;
  }

  /**
   * Indica que o contrato esta habilitado para validar o DV do NN.
   * @return validaDigitoVerificadorNossoNumero
   */
  @javax.annotation.Nonnull
  public Boolean getValidaDigitoVerificadorNossoNumero() {
    return validaDigitoVerificadorNossoNumero;
  }

  public void setValidaDigitoVerificadorNossoNumero(@javax.annotation.Nonnull Boolean validaDigitoVerificadorNossoNumero) {
    this.validaDigitoVerificadorNossoNumero = validaDigitoVerificadorNossoNumero;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FaixaNossoNumero faixaNossoNumero = (FaixaNossoNumero) o;
    return Objects.equals(this.numeroCliente, faixaNossoNumero.numeroCliente) &&
        Objects.equals(this.nomeCliente, faixaNossoNumero.nomeCliente) &&
        Objects.equals(this.numeroInicial, faixaNossoNumero.numeroInicial) &&
        Objects.equals(this.numeroFinal, faixaNossoNumero.numeroFinal) &&
        Objects.equals(this.quantidade, faixaNossoNumero.quantidade) &&
        Objects.equals(this.numeroContratoCobranca, faixaNossoNumero.numeroContratoCobranca) &&
        Objects.equals(this.validaDigitoVerificadorNossoNumero, faixaNossoNumero.validaDigitoVerificadorNossoNumero);
  }

  @Override
  public int hashCode() {
    return Objects.hash(numeroCliente, nomeCliente, numeroInicial, numeroFinal, quantidade, numeroContratoCobranca, validaDigitoVerificadorNossoNumero);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FaixaNossoNumero {\n");
    sb.append("    numeroCliente: ").append(toIndentedString(numeroCliente)).append("\n");
    sb.append("    nomeCliente: ").append(toIndentedString(nomeCliente)).append("\n");
    sb.append("    numeroInicial: ").append(toIndentedString(numeroInicial)).append("\n");
    sb.append("    numeroFinal: ").append(toIndentedString(numeroFinal)).append("\n");
    sb.append("    quantidade: ").append(toIndentedString(quantidade)).append("\n");
    sb.append("    numeroContratoCobranca: ").append(toIndentedString(numeroContratoCobranca)).append("\n");
    sb.append("    validaDigitoVerificadorNossoNumero: ").append(toIndentedString(validaDigitoVerificadorNossoNumero)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("numeroCliente", "nomeCliente", "numeroInicial", "numeroFinal", "quantidade", "numeroContratoCobranca", "validaDigitoVerificadorNossoNumero"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("numeroCliente", "nomeCliente", "numeroInicial", "numeroFinal", "quantidade", "validaDigitoVerificadorNossoNumero"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to FaixaNossoNumero
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!FaixaNossoNumero.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in FaixaNossoNumero is not found in the empty JSON string", FaixaNossoNumero.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!FaixaNossoNumero.openapiFields.contains(entry.getKey())) {
          // throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `FaixaNossoNumero` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : FaixaNossoNumero.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("nomeCliente").isJsonPrimitive()) {
        // throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `nomeCliente` to be a primitive type in the JSON string but got `%s`", jsonObj.get("nomeCliente").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!FaixaNossoNumero.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'FaixaNossoNumero' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<FaixaNossoNumero> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(FaixaNossoNumero.class));

       return (TypeAdapter<T>) new TypeAdapter<FaixaNossoNumero>() {
           @Override
           public void write(JsonWriter out, FaixaNossoNumero value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public FaixaNossoNumero read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of FaixaNossoNumero given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of FaixaNossoNumero
   * @throws IOException if the JSON string is invalid with respect to FaixaNossoNumero
   */
  public static FaixaNossoNumero fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, FaixaNossoNumero.class);
  }

  /**
   * Convert an instance of FaixaNossoNumero to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

