/*
 *  Open Finance - Iniciação de Pagamento 
 * <pre>[ Base URL: https://api.sicoob.com.br/payments/v2/itp ]</pre> A API tem como propósito viabiliza a criação, consulta e autorização dos consentimentos para pagamento entre bancos, instituições financeiras e é acessível também à estabelecimentos comerciais participantes do Open Finance Brasil.
 *
 * The version of the OpenAPI document: 2.1.2.0
 * Contact: tiago.santos@sicoob.com.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.sicoob.openfinance.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import br.com.sicoob.openfinance.JSON;

/**
 * DestinoPagamentoIniciacao
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-05-04T12:32:56.193118-03:00[America/Sao_Paulo]", comments = "Generator version: 7.22.0")
public class DestinoPagamentoIniciacao {
  public static final String SERIALIZED_NAME_CPF_CNPJ = "cpfCnpj";
  @SerializedName(SERIALIZED_NAME_CPF_CNPJ)
  @javax.annotation.Nullable
  private String cpfCnpj;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nullable
  private String name;

  /**
   * Gets or Sets personType
   */
  @JsonAdapter(PersonTypeEnum.Adapter.class)
  public enum PersonTypeEnum {
    PESSOA_JURIDICA("PESSOA_JURIDICA"),
    
    PESSOA_NATURAL("PESSOA_NATURAL");

    private String value;

    PersonTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static PersonTypeEnum fromValue(String value) {
      for (PersonTypeEnum b : PersonTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<PersonTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final PersonTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public PersonTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return PersonTypeEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      PersonTypeEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_PERSON_TYPE = "personType";
  @SerializedName(SERIALIZED_NAME_PERSON_TYPE)
  @javax.annotation.Nonnull
  private PersonTypeEnum personType;

  public DestinoPagamentoIniciacao() {
  }

  public DestinoPagamentoIniciacao cpfCnpj(@javax.annotation.Nullable String cpfCnpj) {
    this.cpfCnpj = cpfCnpj;
    return this;
  }

  /**
   * Get cpfCnpj
   * @return cpfCnpj
   */
  @javax.annotation.Nullable
  public String getCpfCnpj() {
    return cpfCnpj;
  }

  public void setCpfCnpj(@javax.annotation.Nullable String cpfCnpj) {
    this.cpfCnpj = cpfCnpj;
  }


  public DestinoPagamentoIniciacao name(@javax.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }


  public DestinoPagamentoIniciacao personType(@javax.annotation.Nonnull PersonTypeEnum personType) {
    this.personType = personType;
    return this;
  }

  /**
   * Get personType
   * @return personType
   */
  @javax.annotation.Nonnull
  public PersonTypeEnum getPersonType() {
    return personType;
  }

  public void setPersonType(@javax.annotation.Nonnull PersonTypeEnum personType) {
    this.personType = personType;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DestinoPagamentoIniciacao destinoPagamentoIniciacao = (DestinoPagamentoIniciacao) o;
    return Objects.equals(this.cpfCnpj, destinoPagamentoIniciacao.cpfCnpj) &&
        Objects.equals(this.name, destinoPagamentoIniciacao.name) &&
        Objects.equals(this.personType, destinoPagamentoIniciacao.personType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cpfCnpj, name, personType);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DestinoPagamentoIniciacao {\n");
    sb.append("    cpfCnpj: ").append(toIndentedString(cpfCnpj)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    personType: ").append(toIndentedString(personType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("cpfCnpj", "name", "personType"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("personType"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to DestinoPagamentoIniciacao
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!DestinoPagamentoIniciacao.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in DestinoPagamentoIniciacao is not found in the empty JSON string", DestinoPagamentoIniciacao.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!DestinoPagamentoIniciacao.openapiFields.contains(entry.getKey())) {
          // // throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `DestinoPagamentoIniciacao` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
          // Ignoring unknown fields to prevent deserialization errors
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : DestinoPagamentoIniciacao.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("cpfCnpj") != null && !jsonObj.get("cpfCnpj").isJsonNull()) && !jsonObj.get("cpfCnpj").isJsonPrimitive()) {
        // throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `cpfCnpj` to be a primitive type in the JSON string but got `%s`", jsonObj.get("cpfCnpj").toString()));
      }
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        // throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if (!jsonObj.get("personType").isJsonPrimitive()) {
        // throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `personType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("personType").toString()));
      }
      // validate the required field `personType`
      PersonTypeEnum.validateJsonElement(jsonObj.get("personType"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!DestinoPagamentoIniciacao.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'DestinoPagamentoIniciacao' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<DestinoPagamentoIniciacao> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(DestinoPagamentoIniciacao.class));

       return (TypeAdapter<T>) new TypeAdapter<DestinoPagamentoIniciacao>() {
           @Override
           public void write(JsonWriter out, DestinoPagamentoIniciacao value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public DestinoPagamentoIniciacao read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of DestinoPagamentoIniciacao given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of DestinoPagamentoIniciacao
   * @throws IOException if the JSON string is invalid with respect to DestinoPagamentoIniciacao
   */
  public static DestinoPagamentoIniciacao fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, DestinoPagamentoIniciacao.class);
  }

  /**
   * Convert an instance of DestinoPagamentoIniciacao to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

