/*
 * Conta Corrente
 * <pre>[ Base URL: https://api.sicoob.com.br/conta-corrente/v4 ]</pre>  # Conta Corrente API A API de Contas Correntes permite o acesso a dados de conta corrente como Saldo e Extrato. 
 *
 * The version of the OpenAPI document: 2.1.1.43
 * Contact: rafael.alves@sicoob.com.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.sicoob.contacorrente.model;

import br.com.sicoob.contacorrente.model.LancamentoSpuOpenBankingRestDTO;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ExtratoSpuOpenBankingRestDTO
 */
public class ExtratoSpuOpenBankingRestDTOTest {
    private final ExtratoSpuOpenBankingRestDTO model = new ExtratoSpuOpenBankingRestDTO();

    /**
     * Model tests for ExtratoSpuOpenBankingRestDTO
     */
    @Test
    public void testExtratoSpuOpenBankingRestDTO() {
        // TODO: test ExtratoSpuOpenBankingRestDTO
    }

    /**
     * Test the property 'saldoAtual'
     */
    @Test
    public void saldoAtualTest() {
        // TODO: test saldoAtual
    }

    /**
     * Test the property 'saldoBloqueado'
     */
    @Test
    public void saldoBloqueadoTest() {
        // TODO: test saldoBloqueado
    }

    /**
     * Test the property 'saldoLimite'
     */
    @Test
    public void saldoLimiteTest() {
        // TODO: test saldoLimite
    }

    /**
     * Test the property 'saldoAnterior'
     */
    @Test
    public void saldoAnteriorTest() {
        // TODO: test saldoAnterior
    }

    /**
     * Test the property 'saldoBloqueioJudicial'
     */
    @Test
    public void saldoBloqueioJudicialTest() {
        // TODO: test saldoBloqueioJudicial
    }

    /**
     * Test the property 'saldoBloqueioJudicialAnterior'
     */
    @Test
    public void saldoBloqueioJudicialAnteriorTest() {
        // TODO: test saldoBloqueioJudicialAnterior
    }

    /**
     * Test the property 'transacoes'
     */
    @Test
    public void transacoesTest() {
        // TODO: test transacoes
    }

}
