/*
 * Pagamentos PIX
 * <pre>[ Base URL: https://api.sicoob.com.br/pix-pagamentos/v2 ]</pre> API de pagamentos.
 *
 * The version of the OpenAPI document: 2.0.24.6
 * Contact: eduardod.silva@fornecedores.sicoob.com.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.sicoob.pagamentospix.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for DadosDoDestinatRio
 */
public class DadosDoDestinatRioTest {
    private final DadosDoDestinatRio model = new DadosDoDestinatRio();

    /**
     * Model tests for DadosDoDestinatRio
     */
    @Test
    public void testDadosDoDestinatRio() {
        // TODO: test DadosDoDestinatRio
    }

    /**
     * Test the property 'cpfCnpj'
     */
    @Test
    public void cpfCnpjTest() {
        // TODO: test cpfCnpj
    }

}
