/*
 * API PIX
 * <pre>[ Base URL: https://api.sicoob.com.br/pix/api/v2 ]</pre> A API Pix Sicoob é uma forma fácil e segura dos associados gerenciarem os seus recebimentos Pix. Ela permite criar cobranças e validar a situação do pagamento, bem como verificar os Pix recebidos.  Seguindo os padrões definidos pelo Bacen, esta API utiliza as melhores práticas de segurança e possui autenticação com TLS mútuo, como uma medida adicional de proteção.
 *
 * The version of the OpenAPI document: 2.0.23.28
 * Contact: suporte.pix@bcb.gov.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.sicoob.pix.model;

import br.com.sicoob.pix.model.HistRicoDeStatusInner;
import br.com.sicoob.pix.model.InformaEsSobreARejeiODaTentativaDaCobranA;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for HistRicoDeTentativasDeCobranAInner
 */
public class HistRicoDeTentativasDeCobranAInnerTest {
    private final HistRicoDeTentativasDeCobranAInner model = new HistRicoDeTentativasDeCobranAInner();

    /**
     * Model tests for HistRicoDeTentativasDeCobranAInner
     */
    @Test
    public void testHistRicoDeTentativasDeCobranAInner() {
        // TODO: test HistRicoDeTentativasDeCobranAInner
    }

    /**
     * Test the property 'dataLiquidacao'
     */
    @Test
    public void dataLiquidacaoTest() {
        // TODO: test dataLiquidacao
    }

    /**
     * Test the property 'tipo'
     */
    @Test
    public void tipoTest() {
        // TODO: test tipo
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'endToEndId'
     */
    @Test
    public void endToEndIdTest() {
        // TODO: test endToEndId
    }

    /**
     * Test the property 'rejeicao'
     */
    @Test
    public void rejeicaoTest() {
        // TODO: test rejeicao
    }

    /**
     * Test the property 'atualizacao'
     */
    @Test
    public void atualizacaoTest() {
        // TODO: test atualizacao
    }

}
