/*
 * API PIX
 * <pre>[ Base URL: https://api.sicoob.com.br/pix/api/v2 ]</pre> A API Pix Sicoob é uma forma fácil e segura dos associados gerenciarem os seus recebimentos Pix. Ela permite criar cobranças e validar a situação do pagamento, bem como verificar os Pix recebidos.  Seguindo os padrões definidos pelo Bacen, esta API utiliza as melhores práticas de segurança e possui autenticação com TLS mútuo, como uma medida adicional de proteção.
 *
 * The version of the OpenAPI document: 2.0.23.28
 * Contact: suporte.pix@bcb.gov.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.sicoob.pix.model;

import br.com.sicoob.pix.model.DescriODoObjetoDaRecorrNcia;
import br.com.sicoob.pix.model.HistRicoDeStatusInner2;
import br.com.sicoob.pix.model.InformaEsSobreCalendRioDaRecorrNcia;
import br.com.sicoob.pix.model.RecorrenciaBaseValor;
import br.com.sicoob.pix.model.RecorrenciaPayloadAllOfRecebedor;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RecorrenciaPayload
 */
public class RecorrenciaPayloadTest {
    private final RecorrenciaPayload model = new RecorrenciaPayload();

    /**
     * Model tests for RecorrenciaPayload
     */
    @Test
    public void testRecorrenciaPayload() {
        // TODO: test RecorrenciaPayload
    }

    /**
     * Test the property 'vinculo'
     */
    @Test
    public void vinculoTest() {
        // TODO: test vinculo
    }

    /**
     * Test the property 'calendario'
     */
    @Test
    public void calendarioTest() {
        // TODO: test calendario
    }

    /**
     * Test the property 'valor'
     */
    @Test
    public void valorTest() {
        // TODO: test valor
    }

    /**
     * Test the property 'politicaRetentativa'
     */
    @Test
    public void politicaRetentativaTest() {
        // TODO: test politicaRetentativa
    }

    /**
     * Test the property 'atualizacao'
     */
    @Test
    public void atualizacaoTest() {
        // TODO: test atualizacao
    }

    /**
     * Test the property 'idRec'
     */
    @Test
    public void idRecTest() {
        // TODO: test idRec
    }

    /**
     * Test the property 'recebedor'
     */
    @Test
    public void recebedorTest() {
        // TODO: test recebedor
    }

}
