/*
 * API PIX
 * <pre>[ Base URL: https://api.sicoob.com.br/pix/api/v2 ]</pre> A API Pix Sicoob é uma forma fácil e segura dos associados gerenciarem os seus recebimentos Pix. Ela permite criar cobranças e validar a situação do pagamento, bem como verificar os Pix recebidos.  Seguindo os padrões definidos pelo Bacen, esta API utiliza as melhores práticas de segurança e possui autenticação com TLS mútuo, como uma medida adicional de proteção.
 *
 * The version of the OpenAPI document: 2.0.23.28
 * Contact: suporte.pix@bcb.gov.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.sicoob.pix.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Troco1
 */
public class Troco1Test {
    private final Troco1 model = new Troco1();

    /**
     * Model tests for Troco1
     */
    @Test
    public void testTroco1() {
        // TODO: test Troco1
    }

    /**
     * Test the property 'valor'
     */
    @Test
    public void valorTest() {
        // TODO: test valor
    }

    /**
     * Test the property 'modalidadeAlteracao'
     */
    @Test
    public void modalidadeAlteracaoTest() {
        // TODO: test modalidadeAlteracao
    }

    /**
     * Test the property 'modalidadeAgente'
     */
    @Test
    public void modalidadeAgenteTest() {
        // TODO: test modalidadeAgente
    }

    /**
     * Test the property 'prestadorDoServicoDeSaque'
     */
    @Test
    public void prestadorDoServicoDeSaqueTest() {
        // TODO: test prestadorDoServicoDeSaque
    }

}
