/*
 * API PIX
 * <pre>[ Base URL: https://api.sicoob.com.br/pix/api/v2 ]</pre> A API Pix Sicoob é uma forma fácil e segura dos associados gerenciarem os seus recebimentos Pix. Ela permite criar cobranças e validar a situação do pagamento, bem como verificar os Pix recebidos.  Seguindo os padrões definidos pelo Bacen, esta API utiliza as melhores práticas de segurança e possui autenticação com TLS mútuo, como uma medida adicional de proteção.
 *
 * The version of the OpenAPI document: 2.0.23.28
 * Contact: suporte.pix@bcb.gov.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.sicoob.pix.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;



import java.io.IOException;
import java.lang.reflect.Type;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.JsonPrimitive;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonSerializationContext;
import com.google.gson.JsonSerializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonArray;
import com.google.gson.JsonParseException;

import br.com.sicoob.pix.JSON;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-05-04T12:32:37.814990-03:00[America/Sao_Paulo]", comments = "Generator version: 7.22.0")
public class DescontosAplicados extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(DescontosAplicados.class.getName());

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!DescontosAplicados.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'DescontosAplicados' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<DescontosAplicadosOneOf> adapterDescontosAplicadosOneOf = gson.getDelegateAdapter(this, TypeToken.get(DescontosAplicadosOneOf.class));
            final TypeAdapter<DescontosAplicadosOneOf1> adapterDescontosAplicadosOneOf1 = gson.getDelegateAdapter(this, TypeToken.get(DescontosAplicadosOneOf1.class));

            return (TypeAdapter<T>) new TypeAdapter<DescontosAplicados>() {
                @Override
                public void write(JsonWriter out, DescontosAplicados value) throws IOException {
                    if (value == null || value.getActualInstance() == null) {
                        elementAdapter.write(out, null);
                        return;
                    }

                    // check if the actual instance is of the type `DescontosAplicadosOneOf`
                    if (value.getActualInstance() instanceof DescontosAplicadosOneOf) {
                        JsonElement element = adapterDescontosAplicadosOneOf.toJsonTree((DescontosAplicadosOneOf)value.getActualInstance());
                        elementAdapter.write(out, element);
                        return;
                    }
                    // check if the actual instance is of the type `DescontosAplicadosOneOf1`
                    if (value.getActualInstance() instanceof DescontosAplicadosOneOf1) {
                        JsonElement element = adapterDescontosAplicadosOneOf1.toJsonTree((DescontosAplicadosOneOf1)value.getActualInstance());
                        elementAdapter.write(out, element);
                        return;
                    }
                    throw new IOException("Failed to serialize as the type doesn't match oneOf schemas: Object");
                }

                @Override
                public DescontosAplicados read(JsonReader in) throws IOException {
                    Object deserialized = null;
                    JsonElement jsonElement = elementAdapter.read(in);

                    int match = 0;
                    ArrayList<String> errorMessages = new ArrayList<>();
                    TypeAdapter actualAdapter = elementAdapter;

                    // deserialize DescontosAplicadosOneOf
                    try {
                        // validate the JSON object to see if any exception is thrown
                        DescontosAplicadosOneOf.validateJsonElement(jsonElement);
                        actualAdapter = adapterDescontosAplicadosOneOf;
                        match++;
                        log.log(Level.FINER, "Input data matches schema 'DescontosAplicadosOneOf'");
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format(java.util.Locale.ROOT, "Deserialization for DescontosAplicadosOneOf failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'DescontosAplicadosOneOf'", e);
                    }
                    // deserialize DescontosAplicadosOneOf1
                    try {
                        // validate the JSON object to see if any exception is thrown
                        DescontosAplicadosOneOf1.validateJsonElement(jsonElement);
                        actualAdapter = adapterDescontosAplicadosOneOf1;
                        match++;
                        log.log(Level.FINER, "Input data matches schema 'DescontosAplicadosOneOf1'");
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format(java.util.Locale.ROOT, "Deserialization for DescontosAplicadosOneOf1 failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'DescontosAplicadosOneOf1'", e);
                    }

                    if (match == 1) {
                        DescontosAplicados ret = new DescontosAplicados();
                        ret.setActualInstance(actualAdapter.fromJsonTree(jsonElement));
                        return ret;
                    }

                    throw new IOException(String.format(java.util.Locale.ROOT, "Failed deserialization for DescontosAplicados: %d classes match result, expected 1. Detailed failure message for oneOf schemas: %s. JSON: %s", match, errorMessages, jsonElement.toString()));
                }
            }.nullSafe();
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, Class<?>> schemas = new HashMap<String, Class<?>>();

    public DescontosAplicados() {
        super("oneOf", Boolean.FALSE);
    }

    public DescontosAplicados(Object o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("DescontosAplicadosOneOf", DescontosAplicadosOneOf.class);
        schemas.put("DescontosAplicadosOneOf1", DescontosAplicadosOneOf1.class);
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return DescontosAplicados.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check
     * the instance parameter is valid against the oneOf child schemas:
     * Object
     *
     * It could be an instance of the 'oneOf' schemas.
     */
    @Override
    public void setActualInstance(Object instance) {
        if (instance instanceof DescontosAplicadosOneOf) {
            super.setActualInstance(instance);
            return;
        }

        if (instance instanceof DescontosAplicadosOneOf1) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be Object");
    }

    /**
     * Get the actual instance, which can be the following:
     * Object
     *
     * @return The actual instance (Object)
     */
    @SuppressWarnings("unchecked")
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `DescontosAplicadosOneOf`. If the actual instance is not `DescontosAplicadosOneOf`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `DescontosAplicadosOneOf`
     * @throws ClassCastException if the instance is not `DescontosAplicadosOneOf`
     */
    @SuppressWarnings("unchecked")
    public DescontosAplicadosOneOf getDescontosAplicadosOneOf() throws ClassCastException {
        return (DescontosAplicadosOneOf)super.getActualInstance();
    }

    /**
     * Get the actual instance of `DescontosAplicadosOneOf1`. If the actual instance is not `DescontosAplicadosOneOf1`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `DescontosAplicadosOneOf1`
     * @throws ClassCastException if the instance is not `DescontosAplicadosOneOf1`
     */
    @SuppressWarnings("unchecked")
    public DescontosAplicadosOneOf1 getDescontosAplicadosOneOf1() throws ClassCastException {
        return (DescontosAplicadosOneOf1)super.getActualInstance();
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to DescontosAplicados
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        // validate oneOf schemas one by one
        int validCount = 0;
        ArrayList<String> errorMessages = new ArrayList<>();
        // validate the json string with DescontosAplicadosOneOf
        try {
            DescontosAplicadosOneOf.validateJsonElement(jsonElement);
            validCount++;
        } catch (Exception e) {
            errorMessages.add(String.format(java.util.Locale.ROOT, "Deserialization for DescontosAplicadosOneOf failed with `%s`.", e.getMessage()));
            // continue to the next one
        }
        // validate the json string with DescontosAplicadosOneOf1
        try {
            DescontosAplicadosOneOf1.validateJsonElement(jsonElement);
            validCount++;
        } catch (Exception e) {
            errorMessages.add(String.format(java.util.Locale.ROOT, "Deserialization for DescontosAplicadosOneOf1 failed with `%s`.", e.getMessage()));
            // continue to the next one
        }
        if (validCount != 1) {
            throw new IOException(String.format(java.util.Locale.ROOT, "The JSON string is invalid for DescontosAplicados with oneOf schemas: Object. %d class(es) match the result, expected 1. Detailed failure message for oneOf schemas: %s. JSON: %s", validCount, errorMessages, jsonElement.toString()));
        }
    }

    /**
     * Create an instance of DescontosAplicados given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of DescontosAplicados
     * @throws IOException if the JSON string is invalid with respect to DescontosAplicados
     */
    public static DescontosAplicados fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, DescontosAplicados.class);
    }

    /**
     * Convert an instance of DescontosAplicados to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}

