/*
 * API PIX
 * <pre>[ Base URL: https://api.sicoob.com.br/pix/api/v2 ]</pre> A API Pix Sicoob é uma forma fácil e segura dos associados gerenciarem os seus recebimentos Pix. Ela permite criar cobranças e validar a situação do pagamento, bem como verificar os Pix recebidos.  Seguindo os padrões definidos pelo Bacen, esta API utiliza as melhores práticas de segurança e possui autenticação com TLS mútuo, como uma medida adicional de proteção.
 *
 * The version of the OpenAPI document: 2.0.23.28
 * Contact: suporte.pix@bcb.gov.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.sicoob.pix.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import br.com.sicoob.pix.JSON;

/**
 * DevolucaoHorario
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-05-04T12:32:37.814990-03:00[America/Sao_Paulo]", comments = "Generator version: 7.22.0")
public class DevolucaoHorario {
  public static final String SERIALIZED_NAME_SOLICITACAO = "solicitacao";
  @SerializedName(SERIALIZED_NAME_SOLICITACAO)
  @javax.annotation.Nullable
  private OffsetDateTime solicitacao;

  public static final String SERIALIZED_NAME_LIQUIDACAO = "liquidacao";
  @SerializedName(SERIALIZED_NAME_LIQUIDACAO)
  @javax.annotation.Nullable
  private OffsetDateTime liquidacao;

  public DevolucaoHorario() {
  }

  public DevolucaoHorario solicitacao(@javax.annotation.Nullable OffsetDateTime solicitacao) {
    this.solicitacao = solicitacao;
    return this;
  }

  /**
   * Horário no qual a devolução foi solicitada no PSP.
   * @return solicitacao
   */
  @javax.annotation.Nullable
  public OffsetDateTime getSolicitacao() {
    return solicitacao;
  }

  public void setSolicitacao(@javax.annotation.Nullable OffsetDateTime solicitacao) {
    this.solicitacao = solicitacao;
  }


  public DevolucaoHorario liquidacao(@javax.annotation.Nullable OffsetDateTime liquidacao) {
    this.liquidacao = liquidacao;
    return this;
  }

  /**
   * Horário no qual a devolução foi liquidada no PSP.
   * @return liquidacao
   */
  @javax.annotation.Nullable
  public OffsetDateTime getLiquidacao() {
    return liquidacao;
  }

  public void setLiquidacao(@javax.annotation.Nullable OffsetDateTime liquidacao) {
    this.liquidacao = liquidacao;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DevolucaoHorario devolucaoHorario = (DevolucaoHorario) o;
    return Objects.equals(this.solicitacao, devolucaoHorario.solicitacao) &&
        Objects.equals(this.liquidacao, devolucaoHorario.liquidacao);
  }

  @Override
  public int hashCode() {
    return Objects.hash(solicitacao, liquidacao);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DevolucaoHorario {\n");
    sb.append("    solicitacao: ").append(toIndentedString(solicitacao)).append("\n");
    sb.append("    liquidacao: ").append(toIndentedString(liquidacao)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("solicitacao", "liquidacao"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to DevolucaoHorario
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!DevolucaoHorario.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in DevolucaoHorario is not found in the empty JSON string", DevolucaoHorario.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!DevolucaoHorario.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `DevolucaoHorario` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!DevolucaoHorario.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'DevolucaoHorario' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<DevolucaoHorario> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(DevolucaoHorario.class));

       return (TypeAdapter<T>) new TypeAdapter<DevolucaoHorario>() {
           @Override
           public void write(JsonWriter out, DevolucaoHorario value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public DevolucaoHorario read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of DevolucaoHorario given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of DevolucaoHorario
   * @throws IOException if the JSON string is invalid with respect to DevolucaoHorario
   */
  public static DevolucaoHorario fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, DevolucaoHorario.class);
  }

  /**
   * Convert an instance of DevolucaoHorario to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

