/*
 * API PIX
 * <pre>[ Base URL: https://api.sicoob.com.br/pix/api/v2 ]</pre> A API Pix Sicoob é uma forma fácil e segura dos associados gerenciarem os seus recebimentos Pix. Ela permite criar cobranças e validar a situação do pagamento, bem como verificar os Pix recebidos.  Seguindo os padrões definidos pelo Bacen, esta API utiliza as melhores práticas de segurança e possui autenticação com TLS mútuo, como uma medida adicional de proteção.
 *
 * The version of the OpenAPI document: 2.0.23.28
 * Contact: suporte.pix@bcb.gov.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.sicoob.pix.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import br.com.sicoob.pix.JSON;

/**
 * Juro aplicado à cobrança
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-05-04T12:32:37.814990-03:00[America/Sao_Paulo]", comments = "Generator version: 7.22.0")
public class JuroAplicado {
  public static final String SERIALIZED_NAME_MODALIDADE = "modalidade";
  @SerializedName(SERIALIZED_NAME_MODALIDADE)
  @javax.annotation.Nonnull
  private Integer modalidade;

  public static final String SERIALIZED_NAME_VALOR_PERC = "valorPerc";
  @SerializedName(SERIALIZED_NAME_VALOR_PERC)
  @javax.annotation.Nonnull
  private String valorPerc;

  public JuroAplicado() {
  }

  public JuroAplicado modalidade(@javax.annotation.Nonnull Integer modalidade) {
    this.modalidade = modalidade;
    return this;
  }

  /**
   * ##### Modalidade de juros, conforme tabela de domínios. &lt;table&gt;&lt;tr&gt;&lt;th&gt;Descrição&lt;/th&gt;&lt;th&gt;Domínio&lt;/th&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;Valor (dias corridos)&lt;/td&gt;&lt;td&gt;1&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;Percentual ao dia (dias corridos)&lt;/td&gt;&lt;td&gt;2&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;Percentual ao mês (dias corridos)&lt;/td&gt;&lt;td&gt;3&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;Percentual ao ano (dias corridos)&lt;/td&gt;&lt;td&gt;4&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;Valor (dias úteis)&lt;/td&gt;&lt;td&gt;5&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;Percentual ao dia (dias úteis)&lt;/td&gt;&lt;td&gt;6&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;Percentual ao mês (dias úteis)&lt;/td&gt;&lt;td&gt;7&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;Percentual ao ano (dias úteis)&lt;/td&gt;&lt;td&gt;8&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt; 
   * minimum: 1
   * maximum: 8
   * @return modalidade
   */
  @javax.annotation.Nonnull
  public Integer getModalidade() {
    return modalidade;
  }

  public void setModalidade(@javax.annotation.Nonnull Integer modalidade) {
    this.modalidade = modalidade;
  }


  public JuroAplicado valorPerc(@javax.annotation.Nonnull String valorPerc) {
    this.valorPerc = valorPerc;
    return this;
  }

  /**
   * Get valorPerc
   * @return valorPerc
   */
  @javax.annotation.Nonnull
  public String getValorPerc() {
    return valorPerc;
  }

  public void setValorPerc(@javax.annotation.Nonnull String valorPerc) {
    this.valorPerc = valorPerc;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JuroAplicado juroAplicado = (JuroAplicado) o;
    return Objects.equals(this.modalidade, juroAplicado.modalidade) &&
        Objects.equals(this.valorPerc, juroAplicado.valorPerc);
  }

  @Override
  public int hashCode() {
    return Objects.hash(modalidade, valorPerc);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JuroAplicado {\n");
    sb.append("    modalidade: ").append(toIndentedString(modalidade)).append("\n");
    sb.append("    valorPerc: ").append(toIndentedString(valorPerc)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("modalidade", "valorPerc"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("modalidade", "valorPerc"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to JuroAplicado
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!JuroAplicado.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in JuroAplicado is not found in the empty JSON string", JuroAplicado.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!JuroAplicado.openapiFields.contains(entry.getKey())) {
          // throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `JuroAplicado` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : JuroAplicado.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("valorPerc").isJsonPrimitive()) {
        // throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `valorPerc` to be a primitive type in the JSON string but got `%s`", jsonObj.get("valorPerc").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!JuroAplicado.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'JuroAplicado' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<JuroAplicado> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(JuroAplicado.class));

       return (TypeAdapter<T>) new TypeAdapter<JuroAplicado>() {
           @Override
           public void write(JsonWriter out, JuroAplicado value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public JuroAplicado read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of JuroAplicado given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of JuroAplicado
   * @throws IOException if the JSON string is invalid with respect to JuroAplicado
   */
  public static JuroAplicado fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, JuroAplicado.class);
  }

  /**
   * Convert an instance of JuroAplicado to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

