/*
 * API PIX
 * <pre>[ Base URL: https://api.sicoob.com.br/pix/api/v2 ]</pre> A API Pix Sicoob é uma forma fácil e segura dos associados gerenciarem os seus recebimentos Pix. Ela permite criar cobranças e validar a situação do pagamento, bem como verificar os Pix recebidos.  Seguindo os padrões definidos pelo Bacen, esta API utiliza as melhores práticas de segurança e possui autenticação com TLS mútuo, como uma medida adicional de proteção.
 *
 * The version of the OpenAPI document: 2.0.23.28
 * Contact: suporte.pix@bcb.gov.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.sicoob.pix.model;

import java.util.Objects;
import br.com.sicoob.pix.model.Paginacao;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import br.com.sicoob.pix.JSON;

/**
 * Parâmetros utilizados para a realização de uma consulta de locations.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-05-04T12:32:37.814990-03:00[America/Sao_Paulo]", comments = "Generator version: 7.22.0")
public class ParametrosConsultaPayloadLocation {
  public static final String SERIALIZED_NAME_INICIO = "inicio";
  @SerializedName(SERIALIZED_NAME_INICIO)
  @javax.annotation.Nonnull
  private OffsetDateTime inicio;

  public static final String SERIALIZED_NAME_FIM = "fim";
  @SerializedName(SERIALIZED_NAME_FIM)
  @javax.annotation.Nonnull
  private OffsetDateTime fim;

  public static final String SERIALIZED_NAME_TX_ID_PRESENTE = "txIdPresente";
  @SerializedName(SERIALIZED_NAME_TX_ID_PRESENTE)
  @javax.annotation.Nullable
  private Boolean txIdPresente;

  /**
   * Gets or Sets tipoCob
   */
  @JsonAdapter(TipoCobEnum.Adapter.class)
  public enum TipoCobEnum {
    COB("cob"),
    
    COBV("cobv");

    private String value;

    TipoCobEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static TipoCobEnum fromValue(String value) {
      for (TipoCobEnum b : TipoCobEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<TipoCobEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TipoCobEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public TipoCobEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return TipoCobEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      TipoCobEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_TIPO_COB = "tipoCob";
  @SerializedName(SERIALIZED_NAME_TIPO_COB)
  @javax.annotation.Nullable
  private TipoCobEnum tipoCob;

  public static final String SERIALIZED_NAME_PAGINACAO = "paginacao";
  @SerializedName(SERIALIZED_NAME_PAGINACAO)
  @javax.annotation.Nonnull
  private Paginacao paginacao;

  public ParametrosConsultaPayloadLocation() {
  }

  public ParametrosConsultaPayloadLocation inicio(@javax.annotation.Nonnull OffsetDateTime inicio) {
    this.inicio = inicio;
    return this;
  }

  /**
   * Data inicial utilizada na consulta. Respeita RFC 3339.
   * @return inicio
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getInicio() {
    return inicio;
  }

  public void setInicio(@javax.annotation.Nonnull OffsetDateTime inicio) {
    this.inicio = inicio;
  }


  public ParametrosConsultaPayloadLocation fim(@javax.annotation.Nonnull OffsetDateTime fim) {
    this.fim = fim;
    return this;
  }

  /**
   * Data de fim utilizada na consulta. Respeita RFC 3339.
   * @return fim
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getFim() {
    return fim;
  }

  public void setFim(@javax.annotation.Nonnull OffsetDateTime fim) {
    this.fim = fim;
  }


  public ParametrosConsultaPayloadLocation txIdPresente(@javax.annotation.Nullable Boolean txIdPresente) {
    this.txIdPresente = txIdPresente;
    return this;
  }

  /**
   * Filtro pela existência de txid.
   * @return txIdPresente
   */
  @javax.annotation.Nullable
  public Boolean getTxIdPresente() {
    return txIdPresente;
  }

  public void setTxIdPresente(@javax.annotation.Nullable Boolean txIdPresente) {
    this.txIdPresente = txIdPresente;
  }


  public ParametrosConsultaPayloadLocation tipoCob(@javax.annotation.Nullable TipoCobEnum tipoCob) {
    this.tipoCob = tipoCob;
    return this;
  }

  /**
   * Get tipoCob
   * @return tipoCob
   */
  @javax.annotation.Nullable
  public TipoCobEnum getTipoCob() {
    return tipoCob;
  }

  public void setTipoCob(@javax.annotation.Nullable TipoCobEnum tipoCob) {
    this.tipoCob = tipoCob;
  }


  public ParametrosConsultaPayloadLocation paginacao(@javax.annotation.Nonnull Paginacao paginacao) {
    this.paginacao = paginacao;
    return this;
  }

  /**
   * Get paginacao
   * @return paginacao
   */
  @javax.annotation.Nonnull
  public Paginacao getPaginacao() {
    return paginacao;
  }

  public void setPaginacao(@javax.annotation.Nonnull Paginacao paginacao) {
    this.paginacao = paginacao;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ParametrosConsultaPayloadLocation parametrosConsultaPayloadLocation = (ParametrosConsultaPayloadLocation) o;
    return Objects.equals(this.inicio, parametrosConsultaPayloadLocation.inicio) &&
        Objects.equals(this.fim, parametrosConsultaPayloadLocation.fim) &&
        Objects.equals(this.txIdPresente, parametrosConsultaPayloadLocation.txIdPresente) &&
        Objects.equals(this.tipoCob, parametrosConsultaPayloadLocation.tipoCob) &&
        Objects.equals(this.paginacao, parametrosConsultaPayloadLocation.paginacao);
  }

  @Override
  public int hashCode() {
    return Objects.hash(inicio, fim, txIdPresente, tipoCob, paginacao);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ParametrosConsultaPayloadLocation {\n");
    sb.append("    inicio: ").append(toIndentedString(inicio)).append("\n");
    sb.append("    fim: ").append(toIndentedString(fim)).append("\n");
    sb.append("    txIdPresente: ").append(toIndentedString(txIdPresente)).append("\n");
    sb.append("    tipoCob: ").append(toIndentedString(tipoCob)).append("\n");
    sb.append("    paginacao: ").append(toIndentedString(paginacao)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("inicio", "fim", "txIdPresente", "tipoCob", "paginacao"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("inicio", "fim", "paginacao"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ParametrosConsultaPayloadLocation
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ParametrosConsultaPayloadLocation.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in ParametrosConsultaPayloadLocation is not found in the empty JSON string", ParametrosConsultaPayloadLocation.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ParametrosConsultaPayloadLocation.openapiFields.contains(entry.getKey())) {
          // throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `ParametrosConsultaPayloadLocation` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ParametrosConsultaPayloadLocation.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("tipoCob") != null && !jsonObj.get("tipoCob").isJsonNull()) && !jsonObj.get("tipoCob").isJsonPrimitive()) {
        // throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `tipoCob` to be a primitive type in the JSON string but got `%s`", jsonObj.get("tipoCob").toString()));
      }
      // validate the optional field `tipoCob`
      if (jsonObj.get("tipoCob") != null && !jsonObj.get("tipoCob").isJsonNull()) {
        TipoCobEnum.validateJsonElement(jsonObj.get("tipoCob"));
      }
      // validate the required field `paginacao`
      Paginacao.validateJsonElement(jsonObj.get("paginacao"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ParametrosConsultaPayloadLocation.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ParametrosConsultaPayloadLocation' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ParametrosConsultaPayloadLocation> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ParametrosConsultaPayloadLocation.class));

       return (TypeAdapter<T>) new TypeAdapter<ParametrosConsultaPayloadLocation>() {
           @Override
           public void write(JsonWriter out, ParametrosConsultaPayloadLocation value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ParametrosConsultaPayloadLocation read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ParametrosConsultaPayloadLocation given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ParametrosConsultaPayloadLocation
   * @throws IOException if the JSON string is invalid with respect to ParametrosConsultaPayloadLocation
   */
  public static ParametrosConsultaPayloadLocation fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ParametrosConsultaPayloadLocation.class);
  }

  /**
   * Convert an instance of ParametrosConsultaPayloadLocation to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

