/*
 * API PIX
 * <pre>[ Base URL: https://api.sicoob.com.br/pix/api/v2 ]</pre> A API Pix Sicoob é uma forma fácil e segura dos associados gerenciarem os seus recebimentos Pix. Ela permite criar cobranças e validar a situação do pagamento, bem como verificar os Pix recebidos.  Seguindo os padrões definidos pelo Bacen, esta API utiliza as melhores práticas de segurança e possui autenticação com TLS mútuo, como uma medida adicional de proteção.
 *
 * The version of the OpenAPI document: 2.0.23.28
 * Contact: suporte.pix@bcb.gov.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.sicoob.pix.model;

import java.util.Objects;
import br.com.sicoob.pix.model.Paginacao;
import br.com.sicoob.pix.model.Recebedor;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import br.com.sicoob.pix.JSON;

/**
 * Parâmetros utilizados para a realização de uma consulta de cobrança recorrente.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-05-04T12:32:37.814990-03:00[America/Sao_Paulo]", comments = "Generator version: 7.22.0")
public class ParametrosConsultaCobrancaRecorrente {
  public static final String SERIALIZED_NAME_INICIO = "inicio";
  @SerializedName(SERIALIZED_NAME_INICIO)
  @javax.annotation.Nonnull
  private OffsetDateTime inicio;

  public static final String SERIALIZED_NAME_FIM = "fim";
  @SerializedName(SERIALIZED_NAME_FIM)
  @javax.annotation.Nonnull
  private OffsetDateTime fim;

  public static final String SERIALIZED_NAME_CPF = "cpf";
  @SerializedName(SERIALIZED_NAME_CPF)
  @javax.annotation.Nullable
  private String cpf;

  public static final String SERIALIZED_NAME_CNPJ = "cnpj";
  @SerializedName(SERIALIZED_NAME_CNPJ)
  @javax.annotation.Nullable
  private String cnpj;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nullable
  private String status;

  public static final String SERIALIZED_NAME_RECEBEDOR = "recebedor";
  @SerializedName(SERIALIZED_NAME_RECEBEDOR)
  @javax.annotation.Nullable
  private Recebedor recebedor;

  public static final String SERIALIZED_NAME_PAGINACAO = "paginacao";
  @SerializedName(SERIALIZED_NAME_PAGINACAO)
  @javax.annotation.Nonnull
  private Paginacao paginacao;

  public ParametrosConsultaCobrancaRecorrente() {
  }

  public ParametrosConsultaCobrancaRecorrente inicio(@javax.annotation.Nonnull OffsetDateTime inicio) {
    this.inicio = inicio;
    return this;
  }

  /**
   * Data inicial utilizada na consulta. Respeita RFC 3339.
   * @return inicio
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getInicio() {
    return inicio;
  }

  public void setInicio(@javax.annotation.Nonnull OffsetDateTime inicio) {
    this.inicio = inicio;
  }


  public ParametrosConsultaCobrancaRecorrente fim(@javax.annotation.Nonnull OffsetDateTime fim) {
    this.fim = fim;
    return this;
  }

  /**
   * Data de fim utilizada na consulta. Respeita RFC 3339.
   * @return fim
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getFim() {
    return fim;
  }

  public void setFim(@javax.annotation.Nonnull OffsetDateTime fim) {
    this.fim = fim;
  }


  public ParametrosConsultaCobrancaRecorrente cpf(@javax.annotation.Nullable String cpf) {
    this.cpf = cpf;
    return this;
  }

  /**
   * Get cpf
   * @return cpf
   */
  @javax.annotation.Nullable
  public String getCpf() {
    return cpf;
  }

  public void setCpf(@javax.annotation.Nullable String cpf) {
    this.cpf = cpf;
  }


  public ParametrosConsultaCobrancaRecorrente cnpj(@javax.annotation.Nullable String cnpj) {
    this.cnpj = cnpj;
    return this;
  }

  /**
   * Get cnpj
   * @return cnpj
   */
  @javax.annotation.Nullable
  public String getCnpj() {
    return cnpj;
  }

  public void setCnpj(@javax.annotation.Nullable String cnpj) {
    this.cnpj = cnpj;
  }


  public ParametrosConsultaCobrancaRecorrente status(@javax.annotation.Nullable String status) {
    this.status = status;
    return this;
  }

  /**
   * Filtro pelo status das recorrências.
   * @return status
   */
  @javax.annotation.Nullable
  public String getStatus() {
    return status;
  }

  public void setStatus(@javax.annotation.Nullable String status) {
    this.status = status;
  }


  public ParametrosConsultaCobrancaRecorrente recebedor(@javax.annotation.Nullable Recebedor recebedor) {
    this.recebedor = recebedor;
    return this;
  }

  /**
   * Get recebedor
   * @return recebedor
   */
  @javax.annotation.Nullable
  public Recebedor getRecebedor() {
    return recebedor;
  }

  public void setRecebedor(@javax.annotation.Nullable Recebedor recebedor) {
    this.recebedor = recebedor;
  }


  public ParametrosConsultaCobrancaRecorrente paginacao(@javax.annotation.Nonnull Paginacao paginacao) {
    this.paginacao = paginacao;
    return this;
  }

  /**
   * Get paginacao
   * @return paginacao
   */
  @javax.annotation.Nonnull
  public Paginacao getPaginacao() {
    return paginacao;
  }

  public void setPaginacao(@javax.annotation.Nonnull Paginacao paginacao) {
    this.paginacao = paginacao;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ParametrosConsultaCobrancaRecorrente parametrosConsultaCobrancaRecorrente = (ParametrosConsultaCobrancaRecorrente) o;
    return Objects.equals(this.inicio, parametrosConsultaCobrancaRecorrente.inicio) &&
        Objects.equals(this.fim, parametrosConsultaCobrancaRecorrente.fim) &&
        Objects.equals(this.cpf, parametrosConsultaCobrancaRecorrente.cpf) &&
        Objects.equals(this.cnpj, parametrosConsultaCobrancaRecorrente.cnpj) &&
        Objects.equals(this.status, parametrosConsultaCobrancaRecorrente.status) &&
        Objects.equals(this.recebedor, parametrosConsultaCobrancaRecorrente.recebedor) &&
        Objects.equals(this.paginacao, parametrosConsultaCobrancaRecorrente.paginacao);
  }

  @Override
  public int hashCode() {
    return Objects.hash(inicio, fim, cpf, cnpj, status, recebedor, paginacao);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ParametrosConsultaCobrancaRecorrente {\n");
    sb.append("    inicio: ").append(toIndentedString(inicio)).append("\n");
    sb.append("    fim: ").append(toIndentedString(fim)).append("\n");
    sb.append("    cpf: ").append(toIndentedString(cpf)).append("\n");
    sb.append("    cnpj: ").append(toIndentedString(cnpj)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    recebedor: ").append(toIndentedString(recebedor)).append("\n");
    sb.append("    paginacao: ").append(toIndentedString(paginacao)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("inicio", "fim", "cpf", "cnpj", "status", "recebedor", "paginacao"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("inicio", "fim", "paginacao"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ParametrosConsultaCobrancaRecorrente
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ParametrosConsultaCobrancaRecorrente.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in ParametrosConsultaCobrancaRecorrente is not found in the empty JSON string", ParametrosConsultaCobrancaRecorrente.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ParametrosConsultaCobrancaRecorrente.openapiFields.contains(entry.getKey())) {
          // throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `ParametrosConsultaCobrancaRecorrente` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ParametrosConsultaCobrancaRecorrente.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("cpf") != null && !jsonObj.get("cpf").isJsonNull()) && !jsonObj.get("cpf").isJsonPrimitive()) {
        // throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `cpf` to be a primitive type in the JSON string but got `%s`", jsonObj.get("cpf").toString()));
      }
      if ((jsonObj.get("cnpj") != null && !jsonObj.get("cnpj").isJsonNull()) && !jsonObj.get("cnpj").isJsonPrimitive()) {
        // throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `cnpj` to be a primitive type in the JSON string but got `%s`", jsonObj.get("cnpj").toString()));
      }
      if ((jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) && !jsonObj.get("status").isJsonPrimitive()) {
        // throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
      // validate the optional field `recebedor`
      if (jsonObj.get("recebedor") != null && !jsonObj.get("recebedor").isJsonNull()) {
        Recebedor.validateJsonElement(jsonObj.get("recebedor"));
      }
      // validate the required field `paginacao`
      Paginacao.validateJsonElement(jsonObj.get("paginacao"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ParametrosConsultaCobrancaRecorrente.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ParametrosConsultaCobrancaRecorrente' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ParametrosConsultaCobrancaRecorrente> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ParametrosConsultaCobrancaRecorrente.class));

       return (TypeAdapter<T>) new TypeAdapter<ParametrosConsultaCobrancaRecorrente>() {
           @Override
           public void write(JsonWriter out, ParametrosConsultaCobrancaRecorrente value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ParametrosConsultaCobrancaRecorrente read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ParametrosConsultaCobrancaRecorrente given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ParametrosConsultaCobrancaRecorrente
   * @throws IOException if the JSON string is invalid with respect to ParametrosConsultaCobrancaRecorrente
   */
  public static ParametrosConsultaCobrancaRecorrente fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ParametrosConsultaCobrancaRecorrente.class);
  }

  /**
   * Convert an instance of ParametrosConsultaCobrancaRecorrente to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

