/*
 * API PIX
 * <pre>[ Base URL: https://api.sicoob.com.br/pix/api/v2 ]</pre> A API Pix Sicoob é uma forma fácil e segura dos associados gerenciarem os seus recebimentos Pix. Ela permite criar cobranças e validar a situação do pagamento, bem como verificar os Pix recebidos.  Seguindo os padrões definidos pelo Bacen, esta API utiliza as melhores práticas de segurança e possui autenticação com TLS mútuo, como uma medida adicional de proteção.
 *
 * The version of the OpenAPI document: 2.0.23.28
 * Contact: suporte.pix@bcb.gov.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.sicoob.pix.model;

import java.util.Objects;
import br.com.sicoob.pix.model.Violacao;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.net.URI;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import br.com.sicoob.pix.JSON;

/**
 * Problema
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-05-04T12:32:37.814990-03:00[America/Sao_Paulo]", comments = "Generator version: 7.22.0")
public class Problema {
  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  @javax.annotation.Nonnull
  private URI type;

  public static final String SERIALIZED_NAME_TITLE = "title";
  @SerializedName(SERIALIZED_NAME_TITLE)
  @javax.annotation.Nonnull
  private String title;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nonnull
  private Integer status;

  public static final String SERIALIZED_NAME_DETAIL = "detail";
  @SerializedName(SERIALIZED_NAME_DETAIL)
  @javax.annotation.Nullable
  private String detail;

  public static final String SERIALIZED_NAME_CORRELATION_ID = "correlationId";
  @SerializedName(SERIALIZED_NAME_CORRELATION_ID)
  @javax.annotation.Nullable
  private String correlationId;

  public static final String SERIALIZED_NAME_VIOLACOES = "violacoes";
  @SerializedName(SERIALIZED_NAME_VIOLACOES)
  @javax.annotation.Nullable
  private List<Violacao> violacoes = new ArrayList<>();

  public Problema() {
  }

  public Problema type(@javax.annotation.Nonnull URI type) {
    this.type = type;
    return this;
  }

  /**
   * URI de referência que identifica o tipo de problema. De acordo com a RFC 7807.
   * @return type
   */
  @javax.annotation.Nonnull
  public URI getType() {
    return type;
  }

  public void setType(@javax.annotation.Nonnull URI type) {
    this.type = type;
  }


  public Problema title(@javax.annotation.Nonnull String title) {
    this.title = title;
    return this;
  }

  /**
   * Descrição resumida do problema.
   * @return title
   */
  @javax.annotation.Nonnull
  public String getTitle() {
    return title;
  }

  public void setTitle(@javax.annotation.Nonnull String title) {
    this.title = title;
  }


  public Problema status(@javax.annotation.Nonnull Integer status) {
    this.status = status;
    return this;
  }

  /**
   * Código HTTP do status retornado.
   * @return status
   */
  @javax.annotation.Nonnull
  public Integer getStatus() {
    return status;
  }

  public void setStatus(@javax.annotation.Nonnull Integer status) {
    this.status = status;
  }


  public Problema detail(@javax.annotation.Nullable String detail) {
    this.detail = detail;
    return this;
  }

  /**
   * Descrição completa do problema.
   * @return detail
   */
  @javax.annotation.Nullable
  public String getDetail() {
    return detail;
  }

  public void setDetail(@javax.annotation.Nullable String detail) {
    this.detail = detail;
  }


  public Problema correlationId(@javax.annotation.Nullable String correlationId) {
    this.correlationId = correlationId;
    return this;
  }

  /**
   * Identificador de correlação do problema para fins de suporte
   * @return correlationId
   */
  @javax.annotation.Nullable
  public String getCorrelationId() {
    return correlationId;
  }

  public void setCorrelationId(@javax.annotation.Nullable String correlationId) {
    this.correlationId = correlationId;
  }


  public Problema violacoes(@javax.annotation.Nullable List<Violacao> violacoes) {
    this.violacoes = violacoes;
    return this;
  }

  public Problema addViolacoesItem(Violacao violacoesItem) {
    if (this.violacoes == null) {
      this.violacoes = new ArrayList<>();
    }
    this.violacoes.add(violacoesItem);
    return this;
  }

  /**
   * Get violacoes
   * @return violacoes
   */
  @javax.annotation.Nullable
  public List<Violacao> getViolacoes() {
    return violacoes;
  }

  public void setViolacoes(@javax.annotation.Nullable List<Violacao> violacoes) {
    this.violacoes = violacoes;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Problema problema = (Problema) o;
    return Objects.equals(this.type, problema.type) &&
        Objects.equals(this.title, problema.title) &&
        Objects.equals(this.status, problema.status) &&
        Objects.equals(this.detail, problema.detail) &&
        Objects.equals(this.correlationId, problema.correlationId) &&
        Objects.equals(this.violacoes, problema.violacoes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, title, status, detail, correlationId, violacoes);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Problema {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    detail: ").append(toIndentedString(detail)).append("\n");
    sb.append("    correlationId: ").append(toIndentedString(correlationId)).append("\n");
    sb.append("    violacoes: ").append(toIndentedString(violacoes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("type", "title", "status", "detail", "correlationId", "violacoes"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("type", "title", "status"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Problema
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Problema.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in Problema is not found in the empty JSON string", Problema.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Problema.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `Problema` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : Problema.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("type").toString()));
      }
      if (!jsonObj.get("title").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `title` to be a primitive type in the JSON string but got `%s`", jsonObj.get("title").toString()));
      }
      if ((jsonObj.get("detail") != null && !jsonObj.get("detail").isJsonNull()) && !jsonObj.get("detail").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `detail` to be a primitive type in the JSON string but got `%s`", jsonObj.get("detail").toString()));
      }
      if ((jsonObj.get("correlationId") != null && !jsonObj.get("correlationId").isJsonNull()) && !jsonObj.get("correlationId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `correlationId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("correlationId").toString()));
      }
      if (jsonObj.get("violacoes") != null && !jsonObj.get("violacoes").isJsonNull()) {
        JsonArray jsonArrayviolacoes = jsonObj.getAsJsonArray("violacoes");
        if (jsonArrayviolacoes != null) {
          // ensure the json data is an array
          if (!jsonObj.get("violacoes").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `violacoes` to be an array in the JSON string but got `%s`", jsonObj.get("violacoes").toString()));
          }

          // validate the optional field `violacoes` (array)
          for (int i = 0; i < jsonArrayviolacoes.size(); i++) {
            Violacao.validateJsonElement(jsonArrayviolacoes.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Problema.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Problema' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Problema> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Problema.class));

       return (TypeAdapter<T>) new TypeAdapter<Problema>() {
           @Override
           public void write(JsonWriter out, Problema value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Problema read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Problema given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Problema
   * @throws IOException if the JSON string is invalid with respect to Problema
   */
  public static Problema fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Problema.class);
  }

  /**
   * Convert an instance of Problema to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

