/*
 * API PIX
 * <pre>[ Base URL: https://api.sicoob.com.br/pix/api/v2 ]</pre> A API Pix Sicoob é uma forma fácil e segura dos associados gerenciarem os seus recebimentos Pix. Ela permite criar cobranças e validar a situação do pagamento, bem como verificar os Pix recebidos.  Seguindo os padrões definidos pelo Bacen, esta API utiliza as melhores práticas de segurança e possui autenticação com TLS mútuo, como uma medida adicional de proteção.
 *
 * The version of the OpenAPI document: 2.0.23.28
 * Contact: suporte.pix@bcb.gov.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.sicoob.pix.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import br.com.sicoob.pix.JSON;

/**
 * RecorrenciaPayloadAllOfRecebedor
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-05-04T12:32:37.814990-03:00[America/Sao_Paulo]", comments = "Generator version: 7.22.0")
public class RecorrenciaPayloadAllOfRecebedor {
  public static final String SERIALIZED_NAME_CNPJ = "cnpj";
  @SerializedName(SERIALIZED_NAME_CNPJ)
  @javax.annotation.Nonnull
  private String cnpj;

  public static final String SERIALIZED_NAME_NOME = "nome";
  @SerializedName(SERIALIZED_NAME_NOME)
  @javax.annotation.Nonnull
  private String nome;

  public static final String SERIALIZED_NAME_ISPB_PARTICIPANTE = "ispbParticipante";
  @SerializedName(SERIALIZED_NAME_ISPB_PARTICIPANTE)
  @javax.annotation.Nullable
  private String ispbParticipante;

  public static final String SERIALIZED_NAME_AGENCIA = "agencia";
  @SerializedName(SERIALIZED_NAME_AGENCIA)
  @javax.annotation.Nullable
  private String agencia;

  public static final String SERIALIZED_NAME_CONTA = "conta";
  @SerializedName(SERIALIZED_NAME_CONTA)
  @javax.annotation.Nullable
  private String conta;

  public static final String SERIALIZED_NAME_CONVENIO = "convenio";
  @SerializedName(SERIALIZED_NAME_CONVENIO)
  @javax.annotation.Nullable
  private String convenio;

  public RecorrenciaPayloadAllOfRecebedor() {
  }

  public RecorrenciaPayloadAllOfRecebedor cnpj(@javax.annotation.Nonnull String cnpj) {
    this.cnpj = cnpj;
    return this;
  }

  /**
   * Get cnpj
   * @return cnpj
   */
  @javax.annotation.Nonnull
  public String getCnpj() {
    return cnpj;
  }

  public void setCnpj(@javax.annotation.Nonnull String cnpj) {
    this.cnpj = cnpj;
  }


  public RecorrenciaPayloadAllOfRecebedor nome(@javax.annotation.Nonnull String nome) {
    this.nome = nome;
    return this;
  }

  /**
   * Nome do usuário.
   * @return nome
   */
  @javax.annotation.Nonnull
  public String getNome() {
    return nome;
  }

  public void setNome(@javax.annotation.Nonnull String nome) {
    this.nome = nome;
  }


  public RecorrenciaPayloadAllOfRecebedor ispbParticipante(@javax.annotation.Nullable String ispbParticipante) {
    this.ispbParticipante = ispbParticipante;
    return this;
  }

  /**
   * Get ispbParticipante
   * @return ispbParticipante
   */
  @javax.annotation.Nullable
  public String getIspbParticipante() {
    return ispbParticipante;
  }

  public void setIspbParticipante(@javax.annotation.Nullable String ispbParticipante) {
    this.ispbParticipante = ispbParticipante;
  }


  public RecorrenciaPayloadAllOfRecebedor agencia(@javax.annotation.Nullable String agencia) {
    this.agencia = agencia;
    return this;
  }

  /**
   * Agência do usuário recebedor.
   * @return agencia
   */
  @javax.annotation.Nullable
  public String getAgencia() {
    return agencia;
  }

  public void setAgencia(@javax.annotation.Nullable String agencia) {
    this.agencia = agencia;
  }


  public RecorrenciaPayloadAllOfRecebedor conta(@javax.annotation.Nullable String conta) {
    this.conta = conta;
    return this;
  }

  /**
   * Número da conta do usuário recebedor.
   * @return conta
   */
  @javax.annotation.Nullable
  public String getConta() {
    return conta;
  }

  public void setConta(@javax.annotation.Nullable String conta) {
    this.conta = conta;
  }


  public RecorrenciaPayloadAllOfRecebedor convenio(@javax.annotation.Nullable String convenio) {
    this.convenio = convenio;
    return this;
  }

  /**
   * Convênio entre usuário e participante recebedor.
   * @return convenio
   */
  @javax.annotation.Nullable
  public String getConvenio() {
    return convenio;
  }

  public void setConvenio(@javax.annotation.Nullable String convenio) {
    this.convenio = convenio;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RecorrenciaPayloadAllOfRecebedor recorrenciaPayloadAllOfRecebedor = (RecorrenciaPayloadAllOfRecebedor) o;
    return Objects.equals(this.cnpj, recorrenciaPayloadAllOfRecebedor.cnpj) &&
        Objects.equals(this.nome, recorrenciaPayloadAllOfRecebedor.nome) &&
        Objects.equals(this.ispbParticipante, recorrenciaPayloadAllOfRecebedor.ispbParticipante) &&
        Objects.equals(this.agencia, recorrenciaPayloadAllOfRecebedor.agencia) &&
        Objects.equals(this.conta, recorrenciaPayloadAllOfRecebedor.conta) &&
        Objects.equals(this.convenio, recorrenciaPayloadAllOfRecebedor.convenio);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cnpj, nome, ispbParticipante, agencia, conta, convenio);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RecorrenciaPayloadAllOfRecebedor {\n");
    sb.append("    cnpj: ").append(toIndentedString(cnpj)).append("\n");
    sb.append("    nome: ").append(toIndentedString(nome)).append("\n");
    sb.append("    ispbParticipante: ").append(toIndentedString(ispbParticipante)).append("\n");
    sb.append("    agencia: ").append(toIndentedString(agencia)).append("\n");
    sb.append("    conta: ").append(toIndentedString(conta)).append("\n");
    sb.append("    convenio: ").append(toIndentedString(convenio)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("cnpj", "nome", "ispbParticipante", "agencia", "conta", "convenio"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("cnpj", "nome"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to RecorrenciaPayloadAllOfRecebedor
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!RecorrenciaPayloadAllOfRecebedor.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in RecorrenciaPayloadAllOfRecebedor is not found in the empty JSON string", RecorrenciaPayloadAllOfRecebedor.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!RecorrenciaPayloadAllOfRecebedor.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `RecorrenciaPayloadAllOfRecebedor` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : RecorrenciaPayloadAllOfRecebedor.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("cnpj").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `cnpj` to be a primitive type in the JSON string but got `%s`", jsonObj.get("cnpj").toString()));
      }
      if (!jsonObj.get("nome").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `nome` to be a primitive type in the JSON string but got `%s`", jsonObj.get("nome").toString()));
      }
      if ((jsonObj.get("ispbParticipante") != null && !jsonObj.get("ispbParticipante").isJsonNull()) && !jsonObj.get("ispbParticipante").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `ispbParticipante` to be a primitive type in the JSON string but got `%s`", jsonObj.get("ispbParticipante").toString()));
      }
      if ((jsonObj.get("agencia") != null && !jsonObj.get("agencia").isJsonNull()) && !jsonObj.get("agencia").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `agencia` to be a primitive type in the JSON string but got `%s`", jsonObj.get("agencia").toString()));
      }
      if ((jsonObj.get("conta") != null && !jsonObj.get("conta").isJsonNull()) && !jsonObj.get("conta").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `conta` to be a primitive type in the JSON string but got `%s`", jsonObj.get("conta").toString()));
      }
      if ((jsonObj.get("convenio") != null && !jsonObj.get("convenio").isJsonNull()) && !jsonObj.get("convenio").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `convenio` to be a primitive type in the JSON string but got `%s`", jsonObj.get("convenio").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!RecorrenciaPayloadAllOfRecebedor.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'RecorrenciaPayloadAllOfRecebedor' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<RecorrenciaPayloadAllOfRecebedor> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(RecorrenciaPayloadAllOfRecebedor.class));

       return (TypeAdapter<T>) new TypeAdapter<RecorrenciaPayloadAllOfRecebedor>() {
           @Override
           public void write(JsonWriter out, RecorrenciaPayloadAllOfRecebedor value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public RecorrenciaPayloadAllOfRecebedor read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of RecorrenciaPayloadAllOfRecebedor given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of RecorrenciaPayloadAllOfRecebedor
   * @throws IOException if the JSON string is invalid with respect to RecorrenciaPayloadAllOfRecebedor
   */
  public static RecorrenciaPayloadAllOfRecebedor fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, RecorrenciaPayloadAllOfRecebedor.class);
  }

  /**
   * Convert an instance of RecorrenciaPayloadAllOfRecebedor to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

