/*
 * Conta Corrente
 * <pre>[ Base URL: https://api.sicoob.com.br/conta-corrente/v4 ]</pre>  # Conta Corrente API A API de Contas Correntes permite o acesso a dados de conta corrente como Saldo e Extrato. 
 *
 * The version of the OpenAPI document: 2.1.1.43
 * Contact: rafael.alves@sicoob.com.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.sicoob.contacorrente.auth;

import br.com.sicoob.contacorrente.Pair;
import br.com.sicoob.contacorrente.ApiException;

import java.net.URI;
import java.util.Map;
import java.util.List;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-05-04T12:32:48.769273-03:00[America/Sao_Paulo]", comments = "Generator version: 7.22.0")
public interface Authentication {
    /**
     * Apply authentication settings to header and query params.
     *
     * @param queryParams List of query parameters
     * @param headerParams Map of header parameters
     * @param cookieParams Map of cookie parameters
     * @param payload HTTP request body
     * @param method HTTP method
     * @param uri URI
     * @throws ApiException if failed to update the parameters
     */
    void applyToParams(List<Pair> queryParams, Map<String, String> headerParams, Map<String, String> cookieParams, String payload, String method, URI uri) throws ApiException;
}
