/*
 * Pagamentos PIX
 * <pre>[ Base URL: https://api.sicoob.com.br/pix-pagamentos/v2 ]</pre> API de pagamentos.
 *
 * The version of the OpenAPI document: 2.0.24.6
 * Contact: eduardod.silva@fornecedores.sicoob.com.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.sicoob.pagamentospix.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import br.com.sicoob.pagamentospix.JSON;

/**
 * Paginacao
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-05-04T12:32:40.742528-03:00[America/Sao_Paulo]", comments = "Generator version: 7.22.0")
public class Paginacao {
  public static final String SERIALIZED_NAME_PAGINA_ATUAL = "paginaAtual";
  @SerializedName(SERIALIZED_NAME_PAGINA_ATUAL)
  @javax.annotation.Nonnull
  private Integer paginaAtual;

  public static final String SERIALIZED_NAME_ITENS_POR_PAGINA = "itensPorPagina";
  @SerializedName(SERIALIZED_NAME_ITENS_POR_PAGINA)
  @javax.annotation.Nonnull
  private Integer itensPorPagina;

  public static final String SERIALIZED_NAME_QUANTIDADE_DE_PAGINAS = "quantidadeDePaginas";
  @SerializedName(SERIALIZED_NAME_QUANTIDADE_DE_PAGINAS)
  @javax.annotation.Nonnull
  private Integer quantidadeDePaginas;

  public static final String SERIALIZED_NAME_QUANTIDADE_TOTAL_DE_ITENS = "quantidadeTotalDeItens";
  @SerializedName(SERIALIZED_NAME_QUANTIDADE_TOTAL_DE_ITENS)
  @javax.annotation.Nonnull
  private Integer quantidadeTotalDeItens;

  public Paginacao() {
  }

  public Paginacao paginaAtual(@javax.annotation.Nonnull Integer paginaAtual) {
    this.paginaAtual = paginaAtual;
    return this;
  }

  /**
   * Número da página recuperada.
   * minimum: 0
   * @return paginaAtual
   */
  @javax.annotation.Nonnull
  public Integer getPaginaAtual() {
    return paginaAtual;
  }

  public void setPaginaAtual(@javax.annotation.Nonnull Integer paginaAtual) {
    this.paginaAtual = paginaAtual;
  }


  public Paginacao itensPorPagina(@javax.annotation.Nonnull Integer itensPorPagina) {
    this.itensPorPagina = itensPorPagina;
    return this;
  }

  /**
   * Quantidade de registros retornado na página.
   * minimum: 1
   * @return itensPorPagina
   */
  @javax.annotation.Nonnull
  public Integer getItensPorPagina() {
    return itensPorPagina;
  }

  public void setItensPorPagina(@javax.annotation.Nonnull Integer itensPorPagina) {
    this.itensPorPagina = itensPorPagina;
  }


  public Paginacao quantidadeDePaginas(@javax.annotation.Nonnull Integer quantidadeDePaginas) {
    this.quantidadeDePaginas = quantidadeDePaginas;
    return this;
  }

  /**
   * Quantidade de páginas disponíveis para consulta.
   * minimum: 1
   * @return quantidadeDePaginas
   */
  @javax.annotation.Nonnull
  public Integer getQuantidadeDePaginas() {
    return quantidadeDePaginas;
  }

  public void setQuantidadeDePaginas(@javax.annotation.Nonnull Integer quantidadeDePaginas) {
    this.quantidadeDePaginas = quantidadeDePaginas;
  }


  public Paginacao quantidadeTotalDeItens(@javax.annotation.Nonnull Integer quantidadeTotalDeItens) {
    this.quantidadeTotalDeItens = quantidadeTotalDeItens;
    return this;
  }

  /**
   * Quantidade total de itens disponíveis de acordo com os parâmetros informados.
   * minimum: 0
   * @return quantidadeTotalDeItens
   */
  @javax.annotation.Nonnull
  public Integer getQuantidadeTotalDeItens() {
    return quantidadeTotalDeItens;
  }

  public void setQuantidadeTotalDeItens(@javax.annotation.Nonnull Integer quantidadeTotalDeItens) {
    this.quantidadeTotalDeItens = quantidadeTotalDeItens;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Paginacao paginacao = (Paginacao) o;
    return Objects.equals(this.paginaAtual, paginacao.paginaAtual) &&
        Objects.equals(this.itensPorPagina, paginacao.itensPorPagina) &&
        Objects.equals(this.quantidadeDePaginas, paginacao.quantidadeDePaginas) &&
        Objects.equals(this.quantidadeTotalDeItens, paginacao.quantidadeTotalDeItens);
  }

  @Override
  public int hashCode() {
    return Objects.hash(paginaAtual, itensPorPagina, quantidadeDePaginas, quantidadeTotalDeItens);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Paginacao {\n");
    sb.append("    paginaAtual: ").append(toIndentedString(paginaAtual)).append("\n");
    sb.append("    itensPorPagina: ").append(toIndentedString(itensPorPagina)).append("\n");
    sb.append("    quantidadeDePaginas: ").append(toIndentedString(quantidadeDePaginas)).append("\n");
    sb.append("    quantidadeTotalDeItens: ").append(toIndentedString(quantidadeTotalDeItens)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("paginaAtual", "itensPorPagina", "quantidadeDePaginas", "quantidadeTotalDeItens"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("paginaAtual", "itensPorPagina", "quantidadeDePaginas", "quantidadeTotalDeItens"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Paginacao
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Paginacao.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in Paginacao is not found in the empty JSON string", Paginacao.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Paginacao.openapiFields.contains(entry.getKey())) {
          // throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `Paginacao` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : Paginacao.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Paginacao.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Paginacao' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Paginacao> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Paginacao.class));

       return (TypeAdapter<T>) new TypeAdapter<Paginacao>() {
           @Override
           public void write(JsonWriter out, Paginacao value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Paginacao read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Paginacao given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Paginacao
   * @throws IOException if the JSON string is invalid with respect to Paginacao
   */
  public static Paginacao fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Paginacao.class);
  }

  /**
   * Convert an instance of Paginacao to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

