/*
 * API PIX
 * <pre>[ Base URL: https://api.sicoob.com.br/pix/api/v2 ]</pre> A API Pix Sicoob é uma forma fácil e segura dos associados gerenciarem os seus recebimentos Pix. Ela permite criar cobranças e validar a situação do pagamento, bem como verificar os Pix recebidos.  Seguindo os padrões definidos pelo Bacen, esta API utiliza as melhores práticas de segurança e possui autenticação com TLS mútuo, como uma medida adicional de proteção.
 *
 * The version of the OpenAPI document: 2.0.23.28
 * Contact: suporte.pix@bcb.gov.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.sicoob.pix.api;

import br.com.sicoob.pix.ApiException;
import br.com.sicoob.pix.model.CobCompleta;
import br.com.sicoob.pix.model.CobGerada;
import br.com.sicoob.pix.model.CobRevisada;
import br.com.sicoob.pix.model.CobSolicitada;
import br.com.sicoob.pix.model.CobsConsultadas;
import java.io.File;
import java.time.OffsetDateTime;
import br.com.sicoob.pix.model.Problema;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CobApi
 */
@Disabled
public class CobApiTest {

    private final CobApi api = new CobApi();

    /**
     * Consultar lista de cobranças imediatas.
     *
     * Endpoint para consultar cobranças imediatas através de parâmetros como início, fim, cpf, cnpj e status.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void cobGetTest() throws ApiException {
        OffsetDateTime inicio = null;
        OffsetDateTime fim = null;
        String cpf = null;
        String cnpj = null;
        Boolean locationPresente = null;
        String status = null;
        Integer paginacaoPaginaAtual = null;
        Integer paginacaoItensPorPagina = null;
        CobsConsultadas response = api.cobGet(inicio, fim, cpf, cnpj, locationPresente, status, paginacaoPaginaAtual, paginacaoItensPorPagina);
        // TODO: test validations
    }

    /**
     * Criar cobrança imediata.
     *
     * Endpoint para criar uma cobrança imediata, neste caso, o txid deve ser definido pelo PSP.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void cobPostTest() throws ApiException {
        CobSolicitada cobSolicitada = null;
        CobGerada response = api.cobPost(cobSolicitada);
        // TODO: test validations
    }

    /**
     * Consultar cobrança imediata.
     *
     * Endpoint para consultar uma cobrança através de um determinado txid.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void cobTxidGetTest() throws ApiException {
        String txid = null;
        Integer revisao = null;
        CobCompleta response = api.cobTxidGet(txid, revisao);
        // TODO: test validations
    }

    /**
     * Obtem a imagem qrcode de uma cobrança imediata.
     *
     * Endpoint para gerar a imagem qrcode de uma cobrança através de um determinado txid.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void cobTxidImagemGetTest() throws ApiException {
        String txid = null;
        Integer revisao = null;
        Integer largura = null;
        File response = api.cobTxidImagemGet(txid, revisao, largura);
        // TODO: test validations
    }

    /**
     * Revisar cobrança imediata.
     *
     * Endpoint para revisar uma cobrança imediata.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void cobTxidPatchTest() throws ApiException {
        String txid = null;
        CobRevisada cobRevisada = null;
        CobGerada response = api.cobTxidPatch(txid, cobRevisada);
        // TODO: test validations
    }

    /**
     * Criar cobrança imediata.
     *
     * Endpoint para criar uma cobrança imediata.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void cobTxidPutTest() throws ApiException {
        String txid = null;
        CobSolicitada cobSolicitada = null;
        CobGerada response = api.cobTxidPut(txid, cobSolicitada);
        // TODO: test validations
    }

}
