/*
 * Investimentos
 * <pre>[ Base URL: https://api.sicoob.com.br/investimentos/v2 ]</pre> API dedicada a retornar os investimentos de um determinado cliente em várias etapas. Primeira a partir apenas do CPF, depois por carteira e por fim por modalidade
 *
 * The version of the OpenAPI document: 1.0.3.3
 * Contact: tiago.emerick@sicoob.com.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.sicoob.investimentos.model;

import br.com.sicoob.investimentos.model.TabelaDeRendimentos;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Modalidades
 */
public class ModalidadesTest {
    private final Modalidades model = new Modalidades();

    /**
     * Model tests for Modalidades
     */
    @Test
    public void testModalidades() {
        // TODO: test Modalidades
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'sigla'
     */
    @Test
    public void siglaTest() {
        // TODO: test sigla
    }

    /**
     * Test the property 'indice'
     */
    @Test
    public void indiceTest() {
        // TODO: test indice
    }

    /**
     * Test the property 'dataProduto'
     */
    @Test
    public void dataProdutoTest() {
        // TODO: test dataProduto
    }

    /**
     * Test the property 'prazoCarencia'
     */
    @Test
    public void prazoCarenciaTest() {
        // TODO: test prazoCarencia
    }

    /**
     * Test the property 'prazoMaximoAplicacao'
     */
    @Test
    public void prazoMaximoAplicacaoTest() {
        // TODO: test prazoMaximoAplicacao
    }

    /**
     * Test the property 'valorMinimoAplicacao'
     */
    @Test
    public void valorMinimoAplicacaoTest() {
        // TODO: test valorMinimoAplicacao
    }

    /**
     * Test the property 'valorMinimoResgate'
     */
    @Test
    public void valorMinimoResgateTest() {
        // TODO: test valorMinimoResgate
    }

    /**
     * Test the property 'valorMinimoSaldo'
     */
    @Test
    public void valorMinimoSaldoTest() {
        // TODO: test valorMinimoSaldo
    }

    /**
     * Test the property 'prazoMinimoAplicacao'
     */
    @Test
    public void prazoMinimoAplicacaoTest() {
        // TODO: test prazoMinimoAplicacao
    }

    /**
     * Test the property 'tabelaDeRendimentos'
     */
    @Test
    public void tabelaDeRendimentosTest() {
        // TODO: test tabelaDeRendimentos
    }

}
