/*
 * Investimentos
 * <pre>[ Base URL: https://api.sicoob.com.br/investimentos/v2 ]</pre> API dedicada a retornar os investimentos de um determinado cliente em várias etapas. Primeira a partir apenas do CPF, depois por carteira e por fim por modalidade
 *
 * The version of the OpenAPI document: 1.0.3.3
 * Contact: tiago.emerick@sicoob.com.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.sicoob.investimentos.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PrazoIndicesModalidades
 */
public class PrazoIndicesModalidadesTest {
    private final PrazoIndicesModalidades model = new PrazoIndicesModalidades();

    /**
     * Model tests for PrazoIndicesModalidades
     */
    @Test
    public void testPrazoIndicesModalidades() {
        // TODO: test PrazoIndicesModalidades
    }

    /**
     * Test the property 'percIndice'
     */
    @Test
    public void percIndiceTest() {
        // TODO: test percIndice
    }

    /**
     * Test the property 'prazoTaxa'
     */
    @Test
    public void prazoTaxaTest() {
        // TODO: test prazoTaxa
    }

    /**
     * Test the property 'percTaxaMinima'
     */
    @Test
    public void percTaxaMinimaTest() {
        // TODO: test percTaxaMinima
    }

    /**
     * Test the property 'percTaxaMaxima'
     */
    @Test
    public void percTaxaMaximaTest() {
        // TODO: test percTaxaMaxima
    }

}
