/*
 * Investimentos
 * <pre>[ Base URL: https://api.sicoob.com.br/investimentos/v2 ]</pre> API dedicada a retornar os investimentos de um determinado cliente em várias etapas. Primeira a partir apenas do CPF, depois por carteira e por fim por modalidade
 *
 * The version of the OpenAPI document: 1.0.3.3
 * Contact: tiago.emerick@sicoob.com.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.sicoob.investimentos.model;

import br.com.sicoob.investimentos.model.CapRemSicoobMensagemErro;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RendaFixaResgatesPost200Response
 */
public class RendaFixaResgatesPost200ResponseTest {
    private final RendaFixaResgatesPost200Response model = new RendaFixaResgatesPost200Response();

    /**
     * Model tests for RendaFixaResgatesPost200Response
     */
    @Test
    public void testRendaFixaResgatesPost200Response() {
        // TODO: test RendaFixaResgatesPost200Response
    }

    /**
     * Test the property 'mensagens'
     */
    @Test
    public void mensagensTest() {
        // TODO: test mensagens
    }

    /**
     * Test the property 'resultado'
     */
    @Test
    public void resultadoTest() {
        // TODO: test resultado
    }

}
