/*
 * Conta Corrente
 * <pre>[ Base URL: https://api.sicoob.com.br/conta-corrente/v4 ]</pre>  # Conta Corrente API A API de Contas Correntes permite o acesso a dados de conta corrente como Saldo e Extrato. 
 *
 * The version of the OpenAPI document: 2.1.1.43
 * Contact: rafael.alves@sicoob.com.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.sicoob.contacorrente.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import br.com.sicoob.contacorrente.JSON;

/**
 * SicoobMensagemOpenbanking
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-05-04T12:32:48.769273-03:00[America/Sao_Paulo]", comments = "Generator version: 7.22.0")
public class SicoobMensagemOpenbanking {
  public static final String SERIALIZED_NAME_MENSAGEM = "mensagem";
  @SerializedName(SERIALIZED_NAME_MENSAGEM)
  @javax.annotation.Nullable
  private String mensagem;

  public static final String SERIALIZED_NAME_CODIGO = "codigo";
  @SerializedName(SERIALIZED_NAME_CODIGO)
  @javax.annotation.Nullable
  private String codigo;

  public static final String SERIALIZED_NAME_DATA_HORA_OCORRENCIA = "dataHoraOcorrencia";
  @SerializedName(SERIALIZED_NAME_DATA_HORA_OCORRENCIA)
  @javax.annotation.Nullable
  private String dataHoraOcorrencia;

  public static final String SERIALIZED_NAME_SEVERITY = "severity";
  @SerializedName(SERIALIZED_NAME_SEVERITY)
  @javax.annotation.Nullable
  private Integer severity;

  public SicoobMensagemOpenbanking() {
  }

  public SicoobMensagemOpenbanking mensagem(@javax.annotation.Nullable String mensagem) {
    this.mensagem = mensagem;
    return this;
  }

  /**
   * Get mensagem
   * @return mensagem
   */
  @javax.annotation.Nullable
  public String getMensagem() {
    return mensagem;
  }

  public void setMensagem(@javax.annotation.Nullable String mensagem) {
    this.mensagem = mensagem;
  }


  public SicoobMensagemOpenbanking codigo(@javax.annotation.Nullable String codigo) {
    this.codigo = codigo;
    return this;
  }

  /**
   * Get codigo
   * @return codigo
   */
  @javax.annotation.Nullable
  public String getCodigo() {
    return codigo;
  }

  public void setCodigo(@javax.annotation.Nullable String codigo) {
    this.codigo = codigo;
  }


  public SicoobMensagemOpenbanking dataHoraOcorrencia(@javax.annotation.Nullable String dataHoraOcorrencia) {
    this.dataHoraOcorrencia = dataHoraOcorrencia;
    return this;
  }

  /**
   * Get dataHoraOcorrencia
   * @return dataHoraOcorrencia
   */
  @javax.annotation.Nullable
  public String getDataHoraOcorrencia() {
    return dataHoraOcorrencia;
  }

  public void setDataHoraOcorrencia(@javax.annotation.Nullable String dataHoraOcorrencia) {
    this.dataHoraOcorrencia = dataHoraOcorrencia;
  }


  public SicoobMensagemOpenbanking severity(@javax.annotation.Nullable Integer severity) {
    this.severity = severity;
    return this;
  }

  /**
   * Get severity
   * @return severity
   */
  @javax.annotation.Nullable
  public Integer getSeverity() {
    return severity;
  }

  public void setSeverity(@javax.annotation.Nullable Integer severity) {
    this.severity = severity;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SicoobMensagemOpenbanking sicoobMensagemOpenbanking = (SicoobMensagemOpenbanking) o;
    return Objects.equals(this.mensagem, sicoobMensagemOpenbanking.mensagem) &&
        Objects.equals(this.codigo, sicoobMensagemOpenbanking.codigo) &&
        Objects.equals(this.dataHoraOcorrencia, sicoobMensagemOpenbanking.dataHoraOcorrencia) &&
        Objects.equals(this.severity, sicoobMensagemOpenbanking.severity);
  }

  @Override
  public int hashCode() {
    return Objects.hash(mensagem, codigo, dataHoraOcorrencia, severity);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SicoobMensagemOpenbanking {\n");
    sb.append("    mensagem: ").append(toIndentedString(mensagem)).append("\n");
    sb.append("    codigo: ").append(toIndentedString(codigo)).append("\n");
    sb.append("    dataHoraOcorrencia: ").append(toIndentedString(dataHoraOcorrencia)).append("\n");
    sb.append("    severity: ").append(toIndentedString(severity)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("mensagem", "codigo", "dataHoraOcorrencia", "severity"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to SicoobMensagemOpenbanking
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!SicoobMensagemOpenbanking.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in SicoobMensagemOpenbanking is not found in the empty JSON string", SicoobMensagemOpenbanking.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!SicoobMensagemOpenbanking.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `SicoobMensagemOpenbanking` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("mensagem") != null && !jsonObj.get("mensagem").isJsonNull()) && !jsonObj.get("mensagem").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `mensagem` to be a primitive type in the JSON string but got `%s`", jsonObj.get("mensagem").toString()));
      }
      if ((jsonObj.get("codigo") != null && !jsonObj.get("codigo").isJsonNull()) && !jsonObj.get("codigo").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `codigo` to be a primitive type in the JSON string but got `%s`", jsonObj.get("codigo").toString()));
      }
      if ((jsonObj.get("dataHoraOcorrencia") != null && !jsonObj.get("dataHoraOcorrencia").isJsonNull()) && !jsonObj.get("dataHoraOcorrencia").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `dataHoraOcorrencia` to be a primitive type in the JSON string but got `%s`", jsonObj.get("dataHoraOcorrencia").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SicoobMensagemOpenbanking.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SicoobMensagemOpenbanking' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SicoobMensagemOpenbanking> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SicoobMensagemOpenbanking.class));

       return (TypeAdapter<T>) new TypeAdapter<SicoobMensagemOpenbanking>() {
           @Override
           public void write(JsonWriter out, SicoobMensagemOpenbanking value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SicoobMensagemOpenbanking read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of SicoobMensagemOpenbanking given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of SicoobMensagemOpenbanking
   * @throws IOException if the JSON string is invalid with respect to SicoobMensagemOpenbanking
   */
  public static SicoobMensagemOpenbanking fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SicoobMensagemOpenbanking.class);
  }

  /**
   * Convert an instance of SicoobMensagemOpenbanking to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

