/*
 * Conta Corrente
 * <pre>[ Base URL: https://api.sicoob.com.br/conta-corrente/v4 ]</pre>  # Conta Corrente API A API de Contas Correntes permite o acesso a dados de conta corrente como Saldo e Extrato. 
 *
 * The version of the OpenAPI document: 2.1.1.43
 * Contact: rafael.alves@sicoob.com.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.sicoob.contacorrente.model;

import java.util.Objects;
import br.com.sicoob.contacorrente.model.TransferenciaEntreContaDTOCreditorAccount;
import br.com.sicoob.contacorrente.model.TransferenciaEntreContaDTODebtorAccount;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import br.com.sicoob.contacorrente.JSON;

/**
 * TransferenciaEntreContaDTO
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-05-04T12:32:48.769273-03:00[America/Sao_Paulo]", comments = "Generator version: 7.22.0")
public class TransferenciaEntreContaDTO {
  public static final String SERIALIZED_NAME_AMOUNT = "amount";
  @SerializedName(SERIALIZED_NAME_AMOUNT)
  @javax.annotation.Nullable
  private BigDecimal amount;

  public static final String SERIALIZED_NAME_DATE = "date";
  @SerializedName(SERIALIZED_NAME_DATE)
  @javax.annotation.Nullable
  private OffsetDateTime date;

  public static final String SERIALIZED_NAME_DEBTOR_ACCOUNT = "debtorAccount";
  @SerializedName(SERIALIZED_NAME_DEBTOR_ACCOUNT)
  @javax.annotation.Nullable
  private TransferenciaEntreContaDTODebtorAccount debtorAccount;

  public static final String SERIALIZED_NAME_CREDITOR_ACCOUNT = "creditorAccount";
  @SerializedName(SERIALIZED_NAME_CREDITOR_ACCOUNT)
  @javax.annotation.Nullable
  private TransferenciaEntreContaDTOCreditorAccount creditorAccount;

  public TransferenciaEntreContaDTO() {
  }

  public TransferenciaEntreContaDTO amount(@javax.annotation.Nullable BigDecimal amount) {
    this.amount = amount;
    return this;
  }

  /**
   * Quantidade a ser transferida
   * @return amount
   */
  @javax.annotation.Nullable
  public BigDecimal getAmount() {
    return amount;
  }

  public void setAmount(@javax.annotation.Nullable BigDecimal amount) {
    this.amount = amount;
  }


  public TransferenciaEntreContaDTO date(@javax.annotation.Nullable OffsetDateTime date) {
    this.date = date;
    return this;
  }

  /**
   * Data da Transferência
   * @return date
   */
  @javax.annotation.Nullable
  public OffsetDateTime getDate() {
    return date;
  }

  public void setDate(@javax.annotation.Nullable OffsetDateTime date) {
    this.date = date;
  }


  public TransferenciaEntreContaDTO debtorAccount(@javax.annotation.Nullable TransferenciaEntreContaDTODebtorAccount debtorAccount) {
    this.debtorAccount = debtorAccount;
    return this;
  }

  /**
   * Get debtorAccount
   * @return debtorAccount
   */
  @javax.annotation.Nullable
  public TransferenciaEntreContaDTODebtorAccount getDebtorAccount() {
    return debtorAccount;
  }

  public void setDebtorAccount(@javax.annotation.Nullable TransferenciaEntreContaDTODebtorAccount debtorAccount) {
    this.debtorAccount = debtorAccount;
  }


  public TransferenciaEntreContaDTO creditorAccount(@javax.annotation.Nullable TransferenciaEntreContaDTOCreditorAccount creditorAccount) {
    this.creditorAccount = creditorAccount;
    return this;
  }

  /**
   * Get creditorAccount
   * @return creditorAccount
   */
  @javax.annotation.Nullable
  public TransferenciaEntreContaDTOCreditorAccount getCreditorAccount() {
    return creditorAccount;
  }

  public void setCreditorAccount(@javax.annotation.Nullable TransferenciaEntreContaDTOCreditorAccount creditorAccount) {
    this.creditorAccount = creditorAccount;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransferenciaEntreContaDTO transferenciaEntreContaDTO = (TransferenciaEntreContaDTO) o;
    return Objects.equals(this.amount, transferenciaEntreContaDTO.amount) &&
        Objects.equals(this.date, transferenciaEntreContaDTO.date) &&
        Objects.equals(this.debtorAccount, transferenciaEntreContaDTO.debtorAccount) &&
        Objects.equals(this.creditorAccount, transferenciaEntreContaDTO.creditorAccount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(amount, date, debtorAccount, creditorAccount);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransferenciaEntreContaDTO {\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    debtorAccount: ").append(toIndentedString(debtorAccount)).append("\n");
    sb.append("    creditorAccount: ").append(toIndentedString(creditorAccount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("amount", "date", "debtorAccount", "creditorAccount"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to TransferenciaEntreContaDTO
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!TransferenciaEntreContaDTO.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in TransferenciaEntreContaDTO is not found in the empty JSON string", TransferenciaEntreContaDTO.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!TransferenciaEntreContaDTO.openapiFields.contains(entry.getKey())) {
          // throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `TransferenciaEntreContaDTO` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `debtorAccount`
      if (jsonObj.get("debtorAccount") != null && !jsonObj.get("debtorAccount").isJsonNull()) {
        TransferenciaEntreContaDTODebtorAccount.validateJsonElement(jsonObj.get("debtorAccount"));
      }
      // validate the optional field `creditorAccount`
      if (jsonObj.get("creditorAccount") != null && !jsonObj.get("creditorAccount").isJsonNull()) {
        TransferenciaEntreContaDTOCreditorAccount.validateJsonElement(jsonObj.get("creditorAccount"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TransferenciaEntreContaDTO.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TransferenciaEntreContaDTO' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TransferenciaEntreContaDTO> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TransferenciaEntreContaDTO.class));

       return (TypeAdapter<T>) new TypeAdapter<TransferenciaEntreContaDTO>() {
           @Override
           public void write(JsonWriter out, TransferenciaEntreContaDTO value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public TransferenciaEntreContaDTO read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of TransferenciaEntreContaDTO given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of TransferenciaEntreContaDTO
   * @throws IOException if the JSON string is invalid with respect to TransferenciaEntreContaDTO
   */
  public static TransferenciaEntreContaDTO fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TransferenciaEntreContaDTO.class);
  }

  /**
   * Convert an instance of TransferenciaEntreContaDTO to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

