/*
 * Conta Corrente
 * <pre>[ Base URL: https://api.sicoob.com.br/conta-corrente/v4 ]</pre>  # Conta Corrente API A API de Contas Correntes permite o acesso a dados de conta corrente como Saldo e Extrato. 
 *
 * The version of the OpenAPI document: 2.1.1.43
 * Contact: rafael.alves@sicoob.com.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.sicoob.contacorrente.api;

import br.com.sicoob.contacorrente.ApiException;
import br.com.sicoob.contacorrente.model.Saldo;
import br.com.sicoob.contacorrente.model.SicoobMensagem;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SaldoApi
 */
@Disabled
public class SaldoApiTest {

    private final SaldoApi api = new SaldoApi();

    /**
     * O recurso de Saldo retorna o valor disponivel atual, o limite de credito (cheque especial) e o saldo bloqueado de uma conta corrente.
     *
     * Saldo bancario
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void obterSaldoTest() throws ApiException {
        String clientId = null;
        Long numeroContaCorrente = null;
        Saldo response = api.obterSaldo(clientId, numeroContaCorrente);
        // TODO: test validations
    }

}
