/*
 * Conta Corrente
 * <pre>[ Base URL: https://api.sicoob.com.br/conta-corrente/v4 ]</pre>  # Conta Corrente API A API de Contas Correntes permite o acesso a dados de conta corrente como Saldo e Extrato. 
 *
 * The version of the OpenAPI document: 2.1.1.43
 * Contact: rafael.alves@sicoob.com.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.sicoob.contacorrente.api;

import br.com.sicoob.contacorrente.ApiException;
import br.com.sicoob.contacorrente.model.TransferenciaEntreContaDTO;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TransferenciaEntreContasApi
 */
@Disabled
public class TransferenciaEntreContasApiTest {

    private final TransferenciaEntreContasApi api = new TransferenciaEntreContasApi();

    /**
     * Método que transfere os valores entre contas.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void transferirUsingPOSTTest() throws ApiException {
        String clientId = null;
        String idToken = null;
        String xIdempotencyKey = null;
        TransferenciaEntreContaDTO transferenciaEntreContaDTO = null;
        api.transferirUsingPOST(clientId, idToken, xIdempotencyKey, transferenciaEntreContaDTO);
        // TODO: test validations
    }

}
