/*
 * Investimentos
 * <pre>[ Base URL: https://api.sicoob.com.br/investimentos/v2 ]</pre> API dedicada a retornar os investimentos de um determinado cliente em várias etapas. Primeira a partir apenas do CPF, depois por carteira e por fim por modalidade
 *
 * The version of the OpenAPI document: 1.0.3.3
 * Contact: tiago.emerick@sicoob.com.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.sicoob.investimentos.model;

import java.util.Objects;
import br.com.sicoob.investimentos.model.CapRemSicoobMensagemErro;
import br.com.sicoob.investimentos.model.Modalidades;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import br.com.sicoob.investimentos.JSON;

/**
 * RendaFixaModalidadesGet200Response
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-05-04T12:32:53.838971-03:00[America/Sao_Paulo]", comments = "Generator version: 7.22.0")
public class RendaFixaModalidadesGet200Response {
  public static final String SERIALIZED_NAME_MENSAGENS = "mensagens";
  @SerializedName(SERIALIZED_NAME_MENSAGENS)
  @javax.annotation.Nullable
  private List<CapRemSicoobMensagemErro> mensagens = new ArrayList<>();

  public static final String SERIALIZED_NAME_RESULTADO = "resultado";
  @SerializedName(SERIALIZED_NAME_RESULTADO)
  @javax.annotation.Nullable
  private List<Modalidades> resultado = new ArrayList<>();

  public RendaFixaModalidadesGet200Response() {
  }

  public RendaFixaModalidadesGet200Response mensagens(@javax.annotation.Nullable List<CapRemSicoobMensagemErro> mensagens) {
    this.mensagens = mensagens;
    return this;
  }

  public RendaFixaModalidadesGet200Response addMensagensItem(CapRemSicoobMensagemErro mensagensItem) {
    if (this.mensagens == null) {
      this.mensagens = new ArrayList<>();
    }
    this.mensagens.add(mensagensItem);
    return this;
  }

  /**
   * Get mensagens
   * @return mensagens
   */
  @javax.annotation.Nullable
  public List<CapRemSicoobMensagemErro> getMensagens() {
    return mensagens;
  }

  public void setMensagens(@javax.annotation.Nullable List<CapRemSicoobMensagemErro> mensagens) {
    this.mensagens = mensagens;
  }


  public RendaFixaModalidadesGet200Response resultado(@javax.annotation.Nullable List<Modalidades> resultado) {
    this.resultado = resultado;
    return this;
  }

  public RendaFixaModalidadesGet200Response addResultadoItem(Modalidades resultadoItem) {
    if (this.resultado == null) {
      this.resultado = new ArrayList<>();
    }
    this.resultado.add(resultadoItem);
    return this;
  }

  /**
   * Get resultado
   * @return resultado
   */
  @javax.annotation.Nullable
  public List<Modalidades> getResultado() {
    return resultado;
  }

  public void setResultado(@javax.annotation.Nullable List<Modalidades> resultado) {
    this.resultado = resultado;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RendaFixaModalidadesGet200Response rendaFixaModalidadesGet200Response = (RendaFixaModalidadesGet200Response) o;
    return Objects.equals(this.mensagens, rendaFixaModalidadesGet200Response.mensagens) &&
        Objects.equals(this.resultado, rendaFixaModalidadesGet200Response.resultado);
  }

  @Override
  public int hashCode() {
    return Objects.hash(mensagens, resultado);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RendaFixaModalidadesGet200Response {\n");
    sb.append("    mensagens: ").append(toIndentedString(mensagens)).append("\n");
    sb.append("    resultado: ").append(toIndentedString(resultado)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("mensagens", "resultado"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to RendaFixaModalidadesGet200Response
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!RendaFixaModalidadesGet200Response.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in RendaFixaModalidadesGet200Response is not found in the empty JSON string", RendaFixaModalidadesGet200Response.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!RendaFixaModalidadesGet200Response.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `RendaFixaModalidadesGet200Response` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("mensagens") != null && !jsonObj.get("mensagens").isJsonNull()) {
        JsonArray jsonArraymensagens = jsonObj.getAsJsonArray("mensagens");
        if (jsonArraymensagens != null) {
          // ensure the json data is an array
          if (!jsonObj.get("mensagens").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `mensagens` to be an array in the JSON string but got `%s`", jsonObj.get("mensagens").toString()));
          }

          // validate the optional field `mensagens` (array)
          for (int i = 0; i < jsonArraymensagens.size(); i++) {
            CapRemSicoobMensagemErro.validateJsonElement(jsonArraymensagens.get(i));
          };
        }
      }
      if (jsonObj.get("resultado") != null && !jsonObj.get("resultado").isJsonNull()) {
        JsonArray jsonArrayresultado = jsonObj.getAsJsonArray("resultado");
        if (jsonArrayresultado != null) {
          // ensure the json data is an array
          if (!jsonObj.get("resultado").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `resultado` to be an array in the JSON string but got `%s`", jsonObj.get("resultado").toString()));
          }

          // validate the optional field `resultado` (array)
          for (int i = 0; i < jsonArrayresultado.size(); i++) {
            Modalidades.validateJsonElement(jsonArrayresultado.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!RendaFixaModalidadesGet200Response.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'RendaFixaModalidadesGet200Response' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<RendaFixaModalidadesGet200Response> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(RendaFixaModalidadesGet200Response.class));

       return (TypeAdapter<T>) new TypeAdapter<RendaFixaModalidadesGet200Response>() {
           @Override
           public void write(JsonWriter out, RendaFixaModalidadesGet200Response value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public RendaFixaModalidadesGet200Response read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of RendaFixaModalidadesGet200Response given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of RendaFixaModalidadesGet200Response
   * @throws IOException if the JSON string is invalid with respect to RendaFixaModalidadesGet200Response
   */
  public static RendaFixaModalidadesGet200Response fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, RendaFixaModalidadesGet200Response.class);
  }

  /**
   * Convert an instance of RendaFixaModalidadesGet200Response to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

