/*
 * Investimentos
 * <pre>[ Base URL: https://api.sicoob.com.br/investimentos/v2 ]</pre> API dedicada a retornar os investimentos de um determinado cliente em várias etapas. Primeira a partir apenas do CPF, depois por carteira e por fim por modalidade
 *
 * The version of the OpenAPI document: 1.0.3.3
 * Contact: tiago.emerick@sicoob.com.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.sicoob.investimentos.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import br.com.sicoob.investimentos.JSON;

/**
 * ResgateInteligenteCapRem
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-05-04T12:32:53.838971-03:00[America/Sao_Paulo]", comments = "Generator version: 7.22.0")
public class ResgateInteligenteCapRem {
  public static final String SERIALIZED_NAME_VALOR = "valor";
  @SerializedName(SERIALIZED_NAME_VALOR)
  @javax.annotation.Nullable
  private Float valor;

  public ResgateInteligenteCapRem() {
  }

  public ResgateInteligenteCapRem valor(@javax.annotation.Nullable Float valor) {
    this.valor = valor;
    return this;
  }

  /**
   * Valor a ser resgatado.
   * @return valor
   */
  @javax.annotation.Nullable
  public Float getValor() {
    return valor;
  }

  public void setValor(@javax.annotation.Nullable Float valor) {
    this.valor = valor;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResgateInteligenteCapRem resgateInteligenteCapRem = (ResgateInteligenteCapRem) o;
    return Objects.equals(this.valor, resgateInteligenteCapRem.valor);
  }

  @Override
  public int hashCode() {
    return Objects.hash(valor);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResgateInteligenteCapRem {\n");
    sb.append("    valor: ").append(toIndentedString(valor)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("valor"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ResgateInteligenteCapRem
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ResgateInteligenteCapRem.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in ResgateInteligenteCapRem is not found in the empty JSON string", ResgateInteligenteCapRem.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ResgateInteligenteCapRem.openapiFields.contains(entry.getKey())) {
          // throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `ResgateInteligenteCapRem` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ResgateInteligenteCapRem.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ResgateInteligenteCapRem' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ResgateInteligenteCapRem> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ResgateInteligenteCapRem.class));

       return (TypeAdapter<T>) new TypeAdapter<ResgateInteligenteCapRem>() {
           @Override
           public void write(JsonWriter out, ResgateInteligenteCapRem value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ResgateInteligenteCapRem read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ResgateInteligenteCapRem given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ResgateInteligenteCapRem
   * @throws IOException if the JSON string is invalid with respect to ResgateInteligenteCapRem
   */
  public static ResgateInteligenteCapRem fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ResgateInteligenteCapRem.class);
  }

  /**
   * Convert an instance of ResgateInteligenteCapRem to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

